-- CreateTable
CREATE TABLE "public"."average_statistics_csv_tmp_data" (
    "id" INTEGER NOT NULL,
    "score" VARCHAR(10),
    "country" VARCHAR(255),
    "league" VARCHAR(255),
    "team" VARCHAR(255),
    "game_count" VARCHAR(255),
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "average_statistics_csv_tmp_data_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."average_statistics_team_detail_data" (
    "id" INTEGER NOT NULL,
    "situation" VARCHAR(255),
    "team" VARCHAR(100),
    "opposite_team" VARCHAR(100),
    "ha" VARCHAR(1),
    "country" VARCHAR(255),
    "league" VARCHAR(255),
    "exp_stat" VARCHAR(256),
    "donation_stat" VARCHAR(256),
    "shoot_all_stat" VARCHAR(256),
    "shoot_in_stat" VARCHAR(256),
    "shoot_out_stat" VARCHAR(256),
    "block_shoot_stat" VARCHAR(256),
    "big_chance_stat" VARCHAR(256),
    "corner_stat" VARCHAR(256),
    "box_shoot_in_stat" VARCHAR(256),
    "box_shoot_out_stat" VARCHAR(256),
    "goal_post_stat" VARCHAR(256),
    "goal_head_stat" VARCHAR(256),
    "keeper_save_stat" VARCHAR(256),
    "free_kick_stat" VARCHAR(256),
    "offside_stat" VARCHAR(256),
    "foul_stat" VARCHAR(256),
    "yellow_card_stat" VARCHAR(256),
    "red_card_stat" VARCHAR(256),
    "slow_in_stat" VARCHAR(256),
    "box_touch_stat" VARCHAR(256),
    "pass_count_stat" VARCHAR(256),
    "final_third_pass_count_stat" VARCHAR(256),
    "cross_count_stat" VARCHAR(256),
    "tackle_count_stat" VARCHAR(256),
    "clear_count_stat" VARCHAR(256),
    "intercept_count_stat" VARCHAR(256),
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "average_statistics_team_detail_data_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."calc_correlation" (
    "id" SERIAL NOT NULL,
    "file" VARCHAR(255),
    "country" VARCHAR(40),
    "league" VARCHAR(40),
    "home" VARCHAR(255),
    "away" VARCHAR(255),
    "score" VARCHAR(5),
    "chk_body" VARCHAR(40),
    "home_exp_info" VARCHAR(255),
    "away_exp_info" VARCHAR(255),
    "home_in_goal_exp_info" TEXT,
    "away_in_goal_exp_info" TEXT,
    "home_donation_info" VARCHAR(255),
    "away_donation_info" VARCHAR(255),
    "home_shoot_all_info" VARCHAR(255),
    "away_shoot_all_info" VARCHAR(255),
    "home_shoot_in_info" VARCHAR(255),
    "away_shoot_in_info" VARCHAR(255),
    "home_shoot_out_info" VARCHAR(255),
    "away_shoot_out_info" VARCHAR(255),
    "home_block_shoot_info" VARCHAR(255),
    "away_block_shoot_info" VARCHAR(255),
    "home_big_chance_info" VARCHAR(255),
    "away_big_chance_info" VARCHAR(255),
    "home_corner_info" VARCHAR(255),
    "away_corner_info" VARCHAR(255),
    "home_box_shoot_in_info" VARCHAR(255),
    "away_box_shoot_in_info" VARCHAR(255),
    "home_box_shoot_out_info" VARCHAR(255),
    "away_box_shoot_out_info" VARCHAR(255),
    "home_goal_post_info" VARCHAR(255),
    "away_goal_post_info" VARCHAR(255),
    "home_goal_head_info" VARCHAR(255),
    "away_goal_head_info" VARCHAR(255),
    "home_keeper_save_info" VARCHAR(255),
    "away_keeper_save_info" VARCHAR(255),
    "home_free_kick_info" VARCHAR(255),
    "away_free_kick_info" VARCHAR(255),
    "home_offside_info" VARCHAR(255),
    "away_offside_info" VARCHAR(255),
    "home_foul_info" VARCHAR(255),
    "away_foul_info" VARCHAR(255),
    "home_yellow_card_info" VARCHAR(255),
    "away_yellow_card_info" VARCHAR(255),
    "home_red_card_info" VARCHAR(255),
    "away_red_card_info" VARCHAR(255),
    "home_slow_in_info" VARCHAR(255),
    "away_slow_in_info" VARCHAR(255),
    "home_box_touch_info" VARCHAR(255),
    "away_box_touch_info" VARCHAR(255),
    "home_pass_count_info_on_success_ratio" VARCHAR(255),
    "home_pass_count_info_on_success_count" VARCHAR(255),
    "home_pass_count_info_on_try_count" VARCHAR(255),
    "away_pass_count_info_on_success_ratio" VARCHAR(255),
    "away_pass_count_info_on_success_count" VARCHAR(255),
    "away_pass_count_info_on_try_count" VARCHAR(255),
    "home_final_third_pass_count_info_on_success_ratio" VARCHAR(255),
    "home_final_third_pass_count_info_on_success_count" VARCHAR(255),
    "home_final_third_pass_count_info_on_try_count" VARCHAR(255),
    "away_final_third_pass_count_info_on_success_ratio" VARCHAR(255),
    "away_final_third_pass_count_info_on_success_count" VARCHAR(255),
    "away_final_third_pass_count_info_on_try_count" VARCHAR(255),
    "home_cross_count_info_on_success_ratio" VARCHAR(255),
    "home_cross_count_info_on_success_count" VARCHAR(255),
    "home_cross_count_info_on_try_count" VARCHAR(255),
    "away_cross_count_info_on_success_ratio" VARCHAR(255),
    "away_cross_count_info_on_success_count" VARCHAR(255),
    "away_cross_count_info_on_try_count" VARCHAR(255),
    "home_tackle_count_info_on_success_ratio" VARCHAR(255),
    "home_tackle_count_info_on_success_count" VARCHAR(255),
    "home_tackle_count_info_on_try_count" VARCHAR(255),
    "away_tackle_count_info_on_success_ratio" VARCHAR(255),
    "away_tackle_count_info_on_success_count" VARCHAR(255),
    "away_tackle_count_info_on_try_count" VARCHAR(255),
    "home_clear_count_info" VARCHAR(255),
    "away_clear_count_info" VARCHAR(255),
    "home_intercept_count_info" VARCHAR(255),
    "away_intercept_count_info" VARCHAR(255),
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "calc_correlation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."calc_correlation_ranking" (
    "id" SERIAL NOT NULL,
    "country" VARCHAR(255),
    "league" VARCHAR(255),
    "home" VARCHAR(255),
    "away" VARCHAR(255),
    "score" VARCHAR(255),
    "chkBody" TEXT,
    "rank_1th" TEXT,
    "rank_2th" TEXT,
    "rank_3th" TEXT,
    "rank_4th" TEXT,
    "rank_5th" TEXT,
    "rank_6th" TEXT,
    "rank_7th" TEXT,
    "rank_8th" TEXT,
    "rank_9th" TEXT,
    "rank_10th" TEXT,
    "rank_11th" TEXT,
    "rank_12th" TEXT,
    "rank_13th" TEXT,
    "rank_14th" TEXT,
    "rank_15th" TEXT,
    "rank_16th" TEXT,
    "rank_17th" TEXT,
    "rank_18th" TEXT,
    "rank_19th" TEXT,
    "rank_20th" TEXT,
    "rank_21th" TEXT,
    "rank_22th" TEXT,
    "rank_23th" TEXT,
    "rank_24th" TEXT,
    "rank_25th" TEXT,
    "rank_26th" TEXT,
    "rank_27th" TEXT,
    "rank_28th" TEXT,
    "rank_29th" TEXT,
    "rank_30th" TEXT,
    "rank_31th" TEXT,
    "rank_32th" TEXT,
    "rank_33th" TEXT,
    "rank_34th" TEXT,
    "rank_35th" TEXT,
    "rank_36th" TEXT,
    "rank_37th" TEXT,
    "rank_38th" TEXT,
    "rank_39th" TEXT,
    "rank_40th" TEXT,
    "rank_41th" TEXT,
    "rank_42th" TEXT,
    "rank_43th" TEXT,
    "rank_44th" TEXT,
    "rank_45th" TEXT,
    "rank_46th" TEXT,
    "rank_47th" TEXT,
    "rank_48th" TEXT,
    "rank_49th" TEXT,
    "rank_50th" TEXT,
    "rank_51th" TEXT,
    "rank_52th" TEXT,
    "rank_53th" TEXT,
    "rank_54th" TEXT,
    "rank_55th" TEXT,
    "rank_56th" TEXT,
    "rank_57th" TEXT,
    "rank_58th" TEXT,
    "rank_59th" TEXT,
    "rank_60th" TEXT,
    "rank_61th" TEXT,
    "rank_62th" TEXT,
    "rank_63th" TEXT,
    "rank_64th" TEXT,
    "rank_65th" TEXT,
    "rank_66th" TEXT,
    "rank_67th" TEXT,
    "rank_68th" TEXT,
    "rank_69th" TEXT,
    "rank_70th" TEXT,
    "rank_71th" TEXT,
    "rank_72th" TEXT,
    "rank_73th" TEXT,
    "rank_74th" TEXT,
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "calc_correlation_ranking_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."condition_result_data" (
    "data_seq" SERIAL NOT NULL,
    "mail_target_count" CHAR(30),
    "mail_anonymous_target_count" CHAR(30),
    "mail_target_success_count" CHAR(30),
    "mail_target_fail_count" CHAR(30),
    "ex_mail_target_to_no_result_count" CHAR(30),
    "ex_no_fin_data_to_no_result_count" CHAR(30),
    "goal_delete" CHAR(30),
    "alter_target_mail_anonymous" CHAR(30),
    "alter_target_mail_fail" CHAR(30),
    "no_result_count" CHAR(30),
    "err_data" CHAR(30),
    "condition_data" BYTEA NOT NULL,
    "hash" VARCHAR(256),
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "condition_result_data_pkey" PRIMARY KEY ("data_seq")
);

-- CreateTable
CREATE TABLE "public"."country_league_master" (
    "id" SERIAL NOT NULL,
    "country" VARCHAR(50) NOT NULL,
    "league" VARCHAR(50) NOT NULL,
    "team" VARCHAR(100) NOT NULL,
    "link" VARCHAR(200) NOT NULL,
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "country_league_master_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."country_league_season_master" (
    "id" SERIAL NOT NULL,
    "country" VARCHAR(100) NOT NULL,
    "league" VARCHAR(200) NOT NULL,
    "start_season_date" TIMESTAMP(0),
    "end_season_date" TIMESTAMP(0),
    "round" VARCHAR(2),
    "path" VARCHAR(500),
    "disp_valid_flg" VARCHAR(1) NOT NULL DEFAULT '0',
    "upd_stamp" TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "country_league_season_master_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."country_league_summary" (
    "id" SERIAL NOT NULL,
    "country" VARCHAR(50) NOT NULL,
    "league" VARCHAR(50) NOT NULL,
    "data_count" VARCHAR(100) NOT NULL,
    "csv_count" VARCHAR(100) NOT NULL,
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "country_league_summary_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."data" (
    "seq" SERIAL NOT NULL,
    "condition_result_data_seq_id" VARCHAR(3),
    "data_category" CHAR(100),
    "times" CHAR(50),
    "home_rank" CHAR(30),
    "home_team_name" CHAR(100),
    "home_score" CHAR(20) DEFAULT '0',
    "away_rank" CHAR(30),
    "away_team_name" CHAR(100),
    "away_score" CHAR(20) DEFAULT '0',
    "home_exp" CHAR(50),
    "away_exp" CHAR(50),
    "home_in_goal_exp" CHAR(50),
    "away_in_goal_exp" CHAR(50),
    "home_donation" CHAR(50),
    "away_donation" CHAR(50),
    "home_shoot_all" CHAR(3),
    "away_shoot_all" CHAR(30),
    "home_shoot_in" CHAR(30),
    "away_shoot_in" CHAR(30),
    "home_shoot_out" CHAR(30),
    "away_shoot_out" CHAR(30),
    "home_block_shoot" CHAR(30),
    "away_block_shoot" CHAR(30),
    "home_big_chance" CHAR(30),
    "away_big_chance" CHAR(30),
    "home_corner" CHAR(30),
    "away_corner" CHAR(30),
    "home_box_shoot_in" CHAR(30),
    "away_box_shoot_in" CHAR(30),
    "home_box_shoot_out" CHAR(30),
    "away_box_shoot_out" CHAR(30),
    "home_goal_post" CHAR(30),
    "away_goal_post" CHAR(30),
    "home_goal_head" CHAR(30),
    "away_goal_head" CHAR(30),
    "home_keeper_save" CHAR(30),
    "away_keeper_save" CHAR(30),
    "home_free_kick" CHAR(30),
    "away_free_kick" CHAR(30),
    "home_offside" CHAR(30),
    "away_offside" CHAR(30),
    "home_foul" CHAR(30),
    "away_foul" CHAR(30),
    "home_yellow_card" CHAR(30),
    "away_yellow_card" CHAR(30),
    "home_red_card" CHAR(30),
    "away_red_card" CHAR(30),
    "home_slow_in" CHAR(30),
    "away_slow_in" CHAR(30),
    "home_box_touch" CHAR(30),
    "away_box_touch" CHAR(30),
    "home_pass_count" CHAR(30),
    "away_pass_count" CHAR(30),
    "home_long_pass_count" CHAR(30),
    "away_long_pass_count" CHAR(30),
    "home_final_third_pass_count" CHAR(30),
    "away_final_third_pass_count" CHAR(30),
    "home_cross_count" CHAR(30),
    "away_cross_count" CHAR(30),
    "home_tackle_count" CHAR(30),
    "away_tackle_count" CHAR(30),
    "home_clear_count" CHAR(30),
    "away_clear_count" CHAR(30),
    "home_duel_count" CHAR(30),
    "away_duel_count" CHAR(30),
    "home_intercept_count" CHAR(30),
    "away_intercept_count" CHAR(30),
    "record_time" TIMESTAMP(0),
    "weather" CHAR(5),
    "temparature" CHAR(10),
    "humid" CHAR(5),
    "judge_member" CHAR(50),
    "home_manager" CHAR(50),
    "away_manager" CHAR(50),
    "home_formation" CHAR(20),
    "away_formation" CHAR(20),
    "studium" CHAR(250),
    "capacity" CHAR(20),
    "audience" CHAR(20),
    "home_max_getting_scorer" CHAR(50),
    "away_max_getting_scorer" CHAR(50),
    "home_max_getting_scorer_game_situation" CHAR(20),
    "away_max_getting_scorer_game_situation" CHAR(20),
    "home_team_home_score" CHAR(20),
    "home_team_home_lost" CHAR(20),
    "away_team_home_score" CHAR(20),
    "away_team_home_lost" CHAR(20),
    "home_team_away_score" CHAR(20),
    "home_team_away_lost" CHAR(20),
    "away_team_away_score" CHAR(20),
    "away_team_away_lost" CHAR(20),
    "notice_flg" CHAR(8),
    "goal_time" CHAR(8),
    "goal_team_member" TEXT,
    "judge" CHAR(50),
    "home_team_style" CHAR(50),
    "away_team_style" CHAR(50),
    "probablity" CHAR(50),
    "prediction_score_time" CHAR(50),
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "data_pkey" PRIMARY KEY ("seq")
);

-- CreateTable
CREATE TABLE "public"."each_team_score_based_feature_stats" (
    "id" SERIAL NOT NULL,
    "situation" VARCHAR(255),
    "score" VARCHAR(10),
    "country" VARCHAR(255),
    "league" VARCHAR(255),
    "team" VARCHAR(255),
    "home_exp_stat" VARCHAR(256),
    "away_exp_stat" VARCHAR(256),
    "home_in_goal_exp_stat" TEXT,
    "away_in_goal_exp_stat" TEXT,
    "home_donation_stat" VARCHAR(256),
    "away_donation_stat" VARCHAR(256),
    "home_shoot_all_stat" VARCHAR(256),
    "away_shoot_all_stat" VARCHAR(256),
    "home_shoot_in_stat" VARCHAR(256),
    "away_shoot_in_stat" VARCHAR(256),
    "home_shoot_out_stat" VARCHAR(256),
    "away_shoot_out_stat" VARCHAR(256),
    "home_block_shoot_stat" VARCHAR(256),
    "away_block_shoot_stat" VARCHAR(256),
    "home_big_chance_stat" VARCHAR(256),
    "away_big_chance_stat" VARCHAR(256),
    "home_corner_stat" VARCHAR(256),
    "away_corner_stat" VARCHAR(256),
    "home_box_shoot_in_stat" VARCHAR(256),
    "away_box_shoot_in_stat" VARCHAR(256),
    "home_box_shoot_out_stat" VARCHAR(256),
    "away_box_shoot_out_stat" VARCHAR(256),
    "home_goal_post_stat" VARCHAR(256),
    "away_goal_post_stat" VARCHAR(256),
    "home_goal_head_stat" VARCHAR(256),
    "away_goal_head_stat" VARCHAR(256),
    "home_keeper_save_stat" VARCHAR(256),
    "away_keeper_save_stat" VARCHAR(256),
    "home_free_kick_stat" VARCHAR(256),
    "away_free_kick_stat" VARCHAR(256),
    "home_offside_stat" VARCHAR(256),
    "away_offside_stat" VARCHAR(256),
    "home_foul_stat" VARCHAR(256),
    "away_foul_stat" VARCHAR(256),
    "home_yellow_card_stat" VARCHAR(256),
    "away_yellow_card_stat" VARCHAR(256),
    "home_red_card_stat" VARCHAR(256),
    "away_red_card_stat" VARCHAR(256),
    "home_slow_in_stat" VARCHAR(256),
    "away_slow_in_stat" VARCHAR(256),
    "home_box_touch_stat" VARCHAR(256),
    "away_box_touch_stat" VARCHAR(256),
    "home_pass_count_stat" VARCHAR(256),
    "away_pass_count_stat" VARCHAR(256),
    "home_long_pass_count_stat" VARCHAR(256),
    "away_long_pass_count_stat" VARCHAR(256),
    "home_final_third_pass_count_stat" VARCHAR(256),
    "away_final_third_pass_count_stat" VARCHAR(256),
    "home_cross_count_stat" VARCHAR(256),
    "away_cross_count_stat" VARCHAR(256),
    "home_tackle_count_stat" VARCHAR(256),
    "away_tackle_count_stat" VARCHAR(256),
    "home_clear_count_stat" VARCHAR(256),
    "away_clear_count_stat" VARCHAR(256),
    "home_duel_count_stat" VARCHAR(256),
    "away_duel_count_stat" VARCHAR(256),
    "home_intercept_count_stat" VARCHAR(256),
    "away_intercept_count_stat" VARCHAR(256),
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "each_team_score_based_feature_stats_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."future_master" (
    "seq" BIGSERIAL NOT NULL,
    "game_team_category" VARCHAR(50) NOT NULL,
    "future_time" TIMESTAMPTZ(0) NOT NULL,
    "home_rank" CHAR(30),
    "away_rank" CHAR(30),
    "home_team_name" VARCHAR(100),
    "away_team_name" VARCHAR(100),
    "home_max_getting_scorer" VARCHAR(100),
    "away_max_getting_scorer" VARCHAR(100),
    "home_team_home_score" CHAR(30),
    "home_team_home_lost" CHAR(30),
    "away_team_home_score" CHAR(30),
    "away_team_home_lost" CHAR(30),
    "home_team_away_score" CHAR(30),
    "home_team_away_lost" CHAR(30),
    "away_team_away_score" CHAR(30),
    "away_team_away_lost" CHAR(30),
    "game_link" VARCHAR(255),
    "data_time" TIMESTAMPTZ(0),
    "start_flg" VARCHAR(1) NOT NULL DEFAULT '0',
    "register_id" VARCHAR(50),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(50),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "future_master_pkey" PRIMARY KEY ("seq")
);

-- CreateTable
CREATE TABLE "public"."league_score_time_band_stats" (
    "id" SERIAL NOT NULL,
    "country" VARCHAR(50),
    "league" VARCHAR(50),
    "sum_score_value" VARCHAR(50),
    "time_range_area" VARCHAR(200),
    "target" VARCHAR(50),
    "search" VARCHAR(50),
    "ratio" VARCHAR(50),
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "league_score_time_band_stats_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."league_score_time_band_stats_split_score" (
    "id" SERIAL NOT NULL,
    "country" VARCHAR(50),
    "league" VARCHAR(50),
    "home_score_value" VARCHAR(50),
    "away_score_value" VARCHAR(50),
    "home_time_range_area" VARCHAR(200),
    "away_time_range_area" VARCHAR(200),
    "target" VARCHAR(50),
    "search" VARCHAR(50),
    "ratio" VARCHAR(50),
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "league_score_time_band_stats_split_score_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."match_classification_result" (
    "id" SERIAL NOT NULL,
    "classify_mode" VARCHAR(2),
    "data_category" CHAR(100),
    "times" CHAR(50),
    "home_rank" CHAR(30),
    "home_team_name" CHAR(100),
    "home_score" CHAR(20) DEFAULT '0',
    "away_rank" CHAR(30),
    "away_team_name" CHAR(100),
    "away_score" CHAR(20) DEFAULT '0',
    "home_exp" CHAR(50),
    "away_exp" CHAR(50),
    "home_in_goal_exp" CHAR(50),
    "away_in_goal_exp" CHAR(50),
    "home_donation" CHAR(50),
    "away_donation" CHAR(50),
    "home_shoot_all" CHAR(3),
    "away_shoot_all" CHAR(30),
    "home_shoot_in" CHAR(30),
    "away_shoot_in" CHAR(30),
    "home_shoot_out" CHAR(30),
    "away_shoot_out" CHAR(30),
    "home_block_shoot" CHAR(30),
    "away_block_shoot" CHAR(30),
    "home_big_chance" CHAR(30),
    "away_big_chance" CHAR(30),
    "home_corner" CHAR(30),
    "away_corner" CHAR(30),
    "home_box_shoot_in" CHAR(30),
    "away_box_shoot_in" CHAR(30),
    "home_box_shoot_out" CHAR(30),
    "away_box_shoot_out" CHAR(30),
    "home_goal_post" CHAR(30),
    "away_goal_post" CHAR(30),
    "home_goal_head" CHAR(30),
    "away_goal_head" CHAR(30),
    "home_keeper_save" CHAR(30),
    "away_keeper_save" CHAR(30),
    "home_free_kick" CHAR(30),
    "away_free_kick" CHAR(30),
    "home_offside" CHAR(30),
    "away_offside" CHAR(30),
    "home_foul" CHAR(30),
    "away_foul" CHAR(30),
    "home_yellow_card" CHAR(30),
    "away_yellow_card" CHAR(30),
    "home_red_card" CHAR(30),
    "away_red_card" CHAR(30),
    "home_slow_in" CHAR(30),
    "away_slow_in" CHAR(30),
    "home_box_touch" CHAR(30),
    "away_box_touch" CHAR(30),
    "home_pass_count" CHAR(30),
    "away_pass_count" CHAR(30),
    "home_final_third_pass_count" CHAR(30),
    "away_final_third_pass_count" CHAR(30),
    "home_cross_count" CHAR(30),
    "away_cross_count" CHAR(30),
    "home_tackle_count" CHAR(30),
    "away_tackle_count" CHAR(30),
    "home_clear_count" CHAR(30),
    "away_clear_count" CHAR(30),
    "home_intercept_count" CHAR(30),
    "away_intercept_count" CHAR(30),
    "record_time" TIMESTAMP(0),
    "weather" CHAR(5),
    "temparature" CHAR(10),
    "humid" CHAR(5),
    "judge_member" CHAR(50),
    "home_manager" CHAR(50),
    "away_manager" CHAR(50),
    "home_formation" CHAR(20),
    "away_formation" CHAR(20),
    "studium" VARCHAR(300),
    "capacity" CHAR(20),
    "audience" CHAR(20),
    "home_max_getting_scorer" CHAR(50),
    "away_max_getting_scorer" CHAR(50),
    "home_max_getting_scorer_game_situation" CHAR(20),
    "away_max_getting_scorer_game_situation" CHAR(20),
    "home_team_home_score" CHAR(20),
    "home_team_home_lost" CHAR(20),
    "away_team_home_score" CHAR(20),
    "away_team_home_lost" CHAR(20),
    "home_team_away_score" CHAR(20),
    "home_team_away_lost" CHAR(20),
    "away_team_away_score" CHAR(20),
    "away_team_away_lost" CHAR(20),
    "notice_flg" CHAR(8),
    "goal_time" CHAR(8),
    "goal_team_member" CHAR(50),
    "judge" CHAR(50),
    "home_team_style" CHAR(50),
    "away_team_style" CHAR(50),
    "probablity" CHAR(50),
    "prediction_score_time" CHAR(50),
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "match_classification_result_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."match_classification_result_count" (
    "id" SERIAL NOT NULL,
    "country" VARCHAR(50),
    "league" VARCHAR(50),
    "classify_mode" VARCHAR(2),
    "count" VARCHAR(50),
    "remarks" VARCHAR(3000),
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "match_classification_result_count_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."no_goal_match_stats" (
    "id" SERIAL NOT NULL,
    "seq" CHAR(100),
    "data_category" CHAR(100),
    "times" CHAR(50),
    "home_rank" CHAR(30),
    "home_team_name" CHAR(100),
    "home_score" CHAR(20) DEFAULT '0',
    "away_rank" CHAR(30),
    "away_team_name" CHAR(100),
    "away_score" CHAR(20) DEFAULT '0',
    "home_exp" CHAR(50),
    "away_exp" CHAR(50),
    "home_in_goal_exp" CHAR(50),
    "away_in_goal_exp" CHAR(50),
    "home_donation" CHAR(50),
    "away_donation" CHAR(50),
    "home_shoot_all" CHAR(3),
    "away_shoot_all" CHAR(30),
    "home_shoot_in" CHAR(30),
    "away_shoot_in" CHAR(30),
    "home_shoot_out" CHAR(30),
    "away_shoot_out" CHAR(30),
    "home_block_shoot" CHAR(30),
    "away_block_shoot" CHAR(30),
    "home_big_chance" CHAR(30),
    "away_big_chance" CHAR(30),
    "home_corner" CHAR(30),
    "away_corner" CHAR(30),
    "home_box_shoot_in" CHAR(30),
    "away_box_shoot_in" CHAR(30),
    "home_box_shoot_out" CHAR(30),
    "away_box_shoot_out" CHAR(30),
    "home_goal_post" CHAR(30),
    "away_goal_post" CHAR(30),
    "home_goal_head" CHAR(30),
    "away_goal_head" CHAR(30),
    "home_keeper_save" CHAR(30),
    "away_keeper_save" CHAR(30),
    "home_free_kick" CHAR(30),
    "away_free_kick" CHAR(30),
    "home_offside" CHAR(30),
    "away_offside" CHAR(30),
    "home_foul" CHAR(30),
    "away_foul" CHAR(30),
    "home_yellow_card" CHAR(30),
    "away_yellow_card" CHAR(30),
    "home_red_card" CHAR(30),
    "away_red_card" CHAR(30),
    "home_slow_in" CHAR(30),
    "away_slow_in" CHAR(30),
    "home_box_touch" CHAR(30),
    "away_box_touch" CHAR(30),
    "home_pass_count" CHAR(30),
    "away_pass_count" CHAR(30),
    "home_long_pass_count" CHAR(30),
    "away_long_pass_count" CHAR(30),
    "home_final_third_pass_count" CHAR(30),
    "away_final_third_pass_count" CHAR(30),
    "home_cross_count" CHAR(30),
    "away_cross_count" CHAR(30),
    "home_tackle_count" CHAR(30),
    "away_tackle_count" CHAR(30),
    "home_clear_count" CHAR(30),
    "away_clear_count" CHAR(30),
    "home_duel_count" CHAR(30),
    "away_duel_count" CHAR(30),
    "home_intercept_count" CHAR(30),
    "away_intercept_count" CHAR(30),
    "record_time" TIMESTAMP(0),
    "weather" CHAR(5),
    "temparature" CHAR(10),
    "humid" CHAR(5),
    "judge_member" CHAR(50),
    "home_manager" CHAR(50),
    "away_manager" CHAR(50),
    "home_formation" CHAR(20),
    "away_formation" CHAR(20),
    "studium" CHAR(50),
    "capacity" CHAR(20),
    "audience" CHAR(20),
    "home_max_getting_scorer" CHAR(50),
    "away_max_getting_scorer" CHAR(50),
    "home_max_getting_scorer_game_situation" CHAR(20),
    "away_max_getting_scorer_game_situation" CHAR(20),
    "home_team_home_score" CHAR(20),
    "home_team_home_lost" CHAR(20),
    "away_team_home_score" CHAR(20),
    "away_team_home_lost" CHAR(20),
    "home_team_away_score" CHAR(20),
    "home_team_away_lost" CHAR(20),
    "away_team_away_score" CHAR(20),
    "away_team_away_lost" CHAR(20),
    "notice_flg" CHAR(8),
    "goal_time" CHAR(8),
    "goal_team_member" CHAR(50),
    "judge" CHAR(50),
    "home_team_style" CHAR(50),
    "away_team_style" CHAR(50),
    "probablity" CHAR(50),
    "prediction_score_time" CHAR(50),
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "no_goal_match_stats_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."score_based_feature_stats" (
    "id" SERIAL NOT NULL,
    "situation" VARCHAR(255),
    "score" VARCHAR(10),
    "country" VARCHAR(255),
    "league" VARCHAR(255),
    "home_exp_stat" VARCHAR(256),
    "away_exp_stat" VARCHAR(256),
    "home_in_goal_exp_stat" TEXT,
    "away_in_goal_exp_stat" TEXT,
    "home_donation_stat" VARCHAR(256),
    "away_donation_stat" VARCHAR(256),
    "home_shoot_all_stat" VARCHAR(256),
    "away_shoot_all_stat" VARCHAR(256),
    "home_shoot_in_stat" VARCHAR(256),
    "away_shoot_in_stat" VARCHAR(256),
    "home_shoot_out_stat" VARCHAR(256),
    "away_shoot_out_stat" VARCHAR(256),
    "home_block_shoot_stat" VARCHAR(256),
    "away_block_shoot_stat" VARCHAR(256),
    "home_big_chance_stat" VARCHAR(256),
    "away_big_chance_stat" VARCHAR(256),
    "home_corner_stat" VARCHAR(256),
    "away_corner_stat" VARCHAR(256),
    "home_box_shoot_in_stat" VARCHAR(256),
    "away_box_shoot_in_stat" VARCHAR(256),
    "home_box_shoot_out_stat" VARCHAR(256),
    "away_box_shoot_out_stat" VARCHAR(256),
    "home_goal_post_stat" VARCHAR(256),
    "away_goal_post_stat" VARCHAR(256),
    "home_goal_head_stat" VARCHAR(256),
    "away_goal_head_stat" VARCHAR(256),
    "home_keeper_save_stat" VARCHAR(256),
    "away_keeper_save_stat" VARCHAR(256),
    "home_free_kick_stat" VARCHAR(256),
    "away_free_kick_stat" VARCHAR(256),
    "home_offside_stat" VARCHAR(256),
    "away_offside_stat" VARCHAR(256),
    "home_foul_stat" VARCHAR(256),
    "away_foul_stat" VARCHAR(256),
    "home_yellow_card_stat" VARCHAR(256),
    "away_yellow_card_stat" VARCHAR(256),
    "home_red_card_stat" VARCHAR(256),
    "away_red_card_stat" VARCHAR(256),
    "home_slow_in_stat" VARCHAR(256),
    "away_slow_in_stat" VARCHAR(256),
    "home_box_touch_stat" VARCHAR(256),
    "away_box_touch_stat" VARCHAR(256),
    "home_pass_count_stat" VARCHAR(256),
    "away_pass_count_stat" VARCHAR(256),
    "home_long_pass_count_stat" VARCHAR(256),
    "away_long_pass_count_stat" VARCHAR(256),
    "home_final_third_pass_count_stat" VARCHAR(256),
    "away_final_third_pass_count_stat" VARCHAR(256),
    "home_cross_count_stat" VARCHAR(256),
    "away_cross_count_stat" VARCHAR(256),
    "home_tackle_count_stat" VARCHAR(256),
    "away_tackle_count_stat" VARCHAR(256),
    "home_clear_count_stat" VARCHAR(256),
    "away_clear_count_stat" VARCHAR(256),
    "home_duel_count_stat" VARCHAR(256),
    "away_duel_count_stat" VARCHAR(256),
    "home_intercept_count_stat" VARCHAR(256),
    "away_intercept_count_stat" VARCHAR(256),
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "score_based_feature_stats_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."scoring_playstyle_past_data" (
    "id" INTEGER NOT NULL,
    "data_category" VARCHAR(255),
    "home_team_name" VARCHAR(255),
    "away_team_name" VARCHAR(255),
    "diff_home_score" VARCHAR(255),
    "diff_away_score" VARCHAR(255),
    "diff_home_donation" VARCHAR(255),
    "diff_away_donation" VARCHAR(255),
    "diff_home_shoot_all" VARCHAR(255),
    "diff_away_shoot_all" VARCHAR(255),
    "diff_home_shoot_in" VARCHAR(255),
    "diff_away_shoot_in" VARCHAR(255),
    "diff_home_shoot_out" VARCHAR(255),
    "diff_away_shoot_out" VARCHAR(255),
    "diff_home_block_shoot" VARCHAR(255),
    "diff_away_block_shoot" VARCHAR(255),
    "diff_home_big_chance" VARCHAR(255),
    "diff_away_big_chance" VARCHAR(255),
    "diff_home_corner" VARCHAR(255),
    "diff_away_corner" VARCHAR(255),
    "diff_home_box_shoot_in" VARCHAR(255),
    "diff_away_box_shoot_in" VARCHAR(255),
    "diff_home_box_shoot_out" VARCHAR(255),
    "diff_away_box_shoot_out" VARCHAR(255),
    "diff_home_goal_post" VARCHAR(255),
    "diff_away_goal_post" VARCHAR(255),
    "diff_home_goal_head" VARCHAR(255),
    "diff_away_goal_head" VARCHAR(255),
    "diff_home_keeper_save" VARCHAR(255),
    "diff_away_keeper_save" VARCHAR(255),
    "diff_home_free_kick" VARCHAR(255),
    "diff_away_free_kick" VARCHAR(255),
    "diff_home_offside" VARCHAR(255),
    "diff_away_offside" VARCHAR(255),
    "diff_home_foul" VARCHAR(255),
    "diff_away_foul" VARCHAR(255),
    "diff_home_yellow_card" VARCHAR(255),
    "diff_away_yellow_card" VARCHAR(255),
    "diff_home_red_card" VARCHAR(255),
    "diff_away_red_card" VARCHAR(255),
    "diff_home_slow_in" VARCHAR(255),
    "diff_away_slow_in" VARCHAR(255),
    "diff_home_box_touch" VARCHAR(255),
    "diff_away_box_touch" VARCHAR(255),
    "diff_home_pass_count" VARCHAR(255),
    "diff_away_pass_count" VARCHAR(255),
    "diff_home_final_third_pass_count" VARCHAR(255),
    "diff_away_final_third_pass_count" VARCHAR(255),
    "diff_home_cross_count" VARCHAR(255),
    "diff_away_cross_count" VARCHAR(255),
    "diff_home_tackle_count" VARCHAR(255),
    "diff_away_tackle_count" VARCHAR(255),
    "diff_home_clear_count" VARCHAR(255),
    "diff_away_clear_count" VARCHAR(255),
    "diff_home_intercept_count" VARCHAR(255),
    "diff_away_intercept_count" VARCHAR(255),
    "home_play_style" VARCHAR(255),
    "away_play_style" VARCHAR(255),
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "scoring_playstyle_past_data_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."stat_encryption" (
    "id" BIGSERIAL NOT NULL,
    "country" VARCHAR(64),
    "league" VARCHAR(64),
    "home" VARCHAR(128),
    "away" VARCHAR(128),
    "team" VARCHAR(128),
    "chk_body" VARCHAR(20),
    "home_exp_info" TEXT,
    "away_exp_info" TEXT,
    "home_in_goal_exp_info" TEXT,
    "away_in_goal_exp_info" TEXT,
    "home_donation_info" TEXT,
    "away_donation_info" TEXT,
    "home_shoot_all_info" TEXT,
    "away_shoot_all_info" TEXT,
    "home_shoot_in_info" TEXT,
    "away_shoot_in_info" TEXT,
    "home_shoot_out_info" TEXT,
    "away_shoot_out_info" TEXT,
    "home_block_shoot_info" TEXT,
    "away_block_shoot_info" TEXT,
    "home_big_chance_info" TEXT,
    "away_big_chance_info" TEXT,
    "home_corner_info" TEXT,
    "away_corner_info" TEXT,
    "home_box_shoot_in_info" TEXT,
    "away_box_shoot_in_info" TEXT,
    "home_box_shoot_out_info" TEXT,
    "away_box_shoot_out_info" TEXT,
    "home_goal_post_info" TEXT,
    "away_goal_post_info" TEXT,
    "home_goal_head_info" TEXT,
    "away_goal_head_info" TEXT,
    "home_keeper_save_info" TEXT,
    "away_keeper_save_info" TEXT,
    "home_free_kick_info" TEXT,
    "away_free_kick_info" TEXT,
    "home_offside_info" TEXT,
    "away_offside_info" TEXT,
    "home_foul_info" TEXT,
    "away_foul_info" TEXT,
    "home_yellow_card_info" TEXT,
    "away_yellow_card_info" VARCHAR(255),
    "home_red_card_info" TEXT,
    "away_red_card_info" TEXT,
    "home_slow_in_info" TEXT,
    "away_slow_in_info" TEXT,
    "home_box_touch_info" TEXT,
    "away_box_touch_info" TEXT,
    "home_pass_count_info_on_success_count" TEXT,
    "away_pass_count_info_on_success_count" TEXT,
    "home_long_pass_count_info_on_success_count" TEXT,
    "away_long_pass_count_info_on_success_count" TEXT,
    "home_final_third_pass_count_info_on_success_count" TEXT,
    "away_final_third_pass_count_info_on_success_count" TEXT,
    "home_cross_count_info_on_success_count" TEXT,
    "away_cross_count_info_on_success_count" TEXT,
    "home_tackle_count_info_on_success_count" TEXT,
    "away_tackle_count_info_on_success_count" TEXT,
    "home_clear_count_info" TEXT,
    "away_clear_count_info" TEXT,
    "home_duel_count_info" TEXT,
    "away_duel_count_info" TEXT,
    "home_intercept_count_info" TEXT,
    "away_intercept_count_info" TEXT,
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "stat_encryption_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."stat_size_finalize_master" (
    "id" SERIAL NOT NULL,
    "option_num" VARCHAR(1) NOT NULL DEFAULT '0',
    "options" VARCHAR(255) NOT NULL,
    "flg" VARCHAR(1) NOT NULL DEFAULT '0',
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "stat_size_finalize_master_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."surface_overview" (
    "id" SERIAL NOT NULL,
    "country" VARCHAR(128) NOT NULL,
    "league" VARCHAR(128) NOT NULL,
    "game_year" CHAR(4) NOT NULL,
    "game_month" SMALLINT NOT NULL,
    "team" VARCHAR(128) NOT NULL,
    "games" INTEGER NOT NULL DEFAULT 0,
    "rank" INTEGER,
    "win" INTEGER NOT NULL DEFAULT 0,
    "lose" INTEGER NOT NULL DEFAULT 0,
    "draw" INTEGER NOT NULL DEFAULT 0,
    "winning_points" INTEGER NOT NULL DEFAULT 0,
    "home_1st_half_score" TEXT,
    "home_2nd_half_score" TEXT,
    "home_sum_score" TEXT,
    "home_1st_half_score_ratio" VARCHAR(5),
    "home_2nd_half_score_ratio" VARCHAR(5),
    "home_clean_sheet" TEXT,
    "away_1st_half_score" TEXT,
    "away_2nd_half_score" TEXT,
    "away_sum_score" TEXT,
    "away_1st_half_score_ratio" VARCHAR(5),
    "away_2nd_half_score_ratio" VARCHAR(5),
    "away_clean_sheet" TEXT,
    "fail_to_score_game_count" INTEGER NOT NULL DEFAULT 0,
    "consecutive_win_disp" VARCHAR(64),
    "consecutive_lose_disp" VARCHAR(64),
    "unbeaten_streak_count" INTEGER NOT NULL DEFAULT 0,
    "unbeaten_streak_disp" VARCHAR(64),
    "consecutive_score_count" INTEGER NOT NULL DEFAULT 0,
    "consecutive_score_count_disp" VARCHAR(64),
    "first_week_game_win_count" INTEGER NOT NULL DEFAULT 0,
    "first_week_game_lost_count" INTEGER NOT NULL DEFAULT 0,
    "first_week_game_win_disp" VARCHAR(64),
    "mid_week_game_win_count" INTEGER NOT NULL DEFAULT 0,
    "mid_week_game_lost_count" INTEGER NOT NULL DEFAULT 0,
    "mid_week_game_win_disp" VARCHAR(64),
    "last_week_game_win_count" INTEGER NOT NULL DEFAULT 0,
    "last_week_game_lost_count" INTEGER NOT NULL DEFAULT 0,
    "last_week_game_win_disp" VARCHAR(64),
    "home_win_count" INTEGER NOT NULL DEFAULT 0,
    "home_lose_count" INTEGER NOT NULL DEFAULT 0,
    "home_first_goal_count" INTEGER NOT NULL DEFAULT 0,
    "home_win_behind_count" INTEGER NOT NULL DEFAULT 0,
    "home_lose_behind_count" INTEGER NOT NULL DEFAULT 0,
    "home_win_behind_0vs1_count" INTEGER NOT NULL DEFAULT 0,
    "home_lose_behind_1vs0_count" INTEGER NOT NULL DEFAULT 0,
    "home_win_behind_0vs2_count" INTEGER NOT NULL DEFAULT 0,
    "home_lose_behind_2vs0_count" INTEGER NOT NULL DEFAULT 0,
    "home_win_behind_other_count" INTEGER NOT NULL DEFAULT 0,
    "home_lose_behind_other_count" INTEGER NOT NULL DEFAULT 0,
    "home_adversity_disp" VARCHAR(64),
    "away_win_count" INTEGER NOT NULL DEFAULT 0,
    "away_lose_count" INTEGER NOT NULL DEFAULT 0,
    "away_first_goal_count" INTEGER NOT NULL DEFAULT 0,
    "away_win_behind_count" INTEGER NOT NULL DEFAULT 0,
    "away_lose_behind_count" INTEGER NOT NULL DEFAULT 0,
    "away_win_behind_1vs0_count" INTEGER NOT NULL DEFAULT 0,
    "away_lose_behind_0vs1_count" INTEGER NOT NULL DEFAULT 0,
    "away_win_behind_2vs0_count" INTEGER NOT NULL DEFAULT 0,
    "away_lose_behind_0vs2_count" INTEGER NOT NULL DEFAULT 0,
    "away_win_behind_other_count" INTEGER NOT NULL DEFAULT 0,
    "away_lose_behind_other_count" INTEGER NOT NULL DEFAULT 0,
    "away_adversity_disp" VARCHAR(64),
    "promote_disp" VARCHAR(64),
    "descend_disp" VARCHAR(64),
    "first_win_disp" VARCHAR(64),
    "lose_streak_disp" VARCHAR(64),
    "round_conc" TEXT,
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "surface_overview_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."team_match_final_stats" (
    "seq" SERIAL NOT NULL,
    "team_name" VARCHAR(255),
    "versus_team_name" VARCHAR(255),
    "ha" VARCHAR(1),
    "score" VARCHAR(10),
    "result" VARCHAR(10),
    "game_fin_rank" VARCHAR(255),
    "opposite_game_fin_rank" VARCHAR(255),
    "exp" VARCHAR(255),
    "opposite_exp" VARCHAR(255),
    "in_goal_exp" TEXT,
    "opposite_in_goal_exp" TEXT,
    "donation" VARCHAR(255),
    "opposite_donation" VARCHAR(255),
    "shoot_all" VARCHAR(255),
    "opposite_shoot_all" VARCHAR(255),
    "shoot_in" VARCHAR(255),
    "opposite_shoot_in" VARCHAR(255),
    "shoot_out" VARCHAR(255),
    "opposite_shoot_out" VARCHAR(255),
    "block_shoot" VARCHAR(255),
    "opposite_block_shoot" VARCHAR(255),
    "big_chance" VARCHAR(255),
    "opposite_big_chance" VARCHAR(255),
    "corner" VARCHAR(255),
    "opposite_corner" VARCHAR(255),
    "box_shoot_in" VARCHAR(255),
    "opposite_box_shoot_in" VARCHAR(255),
    "box_shoot_out" VARCHAR(255),
    "opposite_box_shoot_out" VARCHAR(255),
    "goal_post" VARCHAR(255),
    "opposite_goal_post" VARCHAR(255),
    "goal_head" VARCHAR(255),
    "opposite_goal_head" VARCHAR(255),
    "keeper_save" VARCHAR(255),
    "opposite_keeper_save" VARCHAR(255),
    "free_kick" VARCHAR(255),
    "opposite_free_kick" VARCHAR(255),
    "offside" VARCHAR(255),
    "opposite_offside" VARCHAR(255),
    "foul" VARCHAR(255),
    "opposite_foul" VARCHAR(255),
    "yellow_card" VARCHAR(255),
    "opposite_yellow_card" VARCHAR(255),
    "red_card" VARCHAR(255),
    "opposite_red_card" VARCHAR(255),
    "slow_in" VARCHAR(255),
    "opposite_slow_in" VARCHAR(255),
    "box_touch" VARCHAR(255),
    "opposite_box_touch" VARCHAR(255),
    "pass_count_success_ratio" VARCHAR(255),
    "pass_count_success_count" VARCHAR(255),
    "pass_count_try_count" VARCHAR(255),
    "opposite_pass_count_success_ratio" VARCHAR(255),
    "opposite_pass_count_success_count" VARCHAR(255),
    "opposite_pass_count_try_count" VARCHAR(255),
    "long_pass_count_success_ratio" VARCHAR(255),
    "long_pass_count_success_count" VARCHAR(255),
    "long_pass_count_try_count" VARCHAR(255),
    "opposite_long_pass_count_success_ratio" VARCHAR(255),
    "opposite_long_pass_count_success_count" VARCHAR(255),
    "opposite_long_pass_count_try_count" VARCHAR(255),
    "final_third_pass_count_success_ratio" VARCHAR(255),
    "final_third_pass_count_success_count" VARCHAR(255),
    "final_third_pass_count_try_count" VARCHAR(255),
    "opposite_final_third_pass_count_success_ratio" VARCHAR(255),
    "opposite_final_third_pass_count_success_count" VARCHAR(255),
    "opposite_final_third_pass_count_try_count" VARCHAR(255),
    "cross_count_success_ratio" VARCHAR(255),
    "cross_count_success_count" VARCHAR(255),
    "cross_count_try_count" VARCHAR(255),
    "opposite_cross_count_success_ratio" VARCHAR(255),
    "opposite_cross_count_success_count" VARCHAR(255),
    "opposite_cross_count_try_count" VARCHAR(255),
    "tackle_count_success_ratio" VARCHAR(255),
    "tackle_count_success_count" VARCHAR(255),
    "tackle_count_try_count" VARCHAR(255),
    "opposite_tackle_count_success_ratio" VARCHAR(255),
    "opposite_tackle_count_success_count" VARCHAR(255),
    "opposite_tackle_count_try_count" VARCHAR(255),
    "clear_count" VARCHAR(255),
    "opposite_clear_count" VARCHAR(255),
    "duel_count" VARCHAR(255),
    "opposite_duel_count" VARCHAR(255),
    "intercept_count" VARCHAR(255),
    "opposite_intercept_count" VARCHAR(255),
    "weather" VARCHAR(255),
    "temperature" VARCHAR(255),
    "humid" VARCHAR(255),
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "team_match_final_stats_pkey" PRIMARY KEY ("seq")
);

-- CreateTable
CREATE TABLE "public"."team_member_master" (
    "id" SERIAL NOT NULL,
    "country" TEXT,
    "league" TEXT,
    "team" VARCHAR(255) NOT NULL,
    "score" TEXT,
    "loan_belong" TEXT,
    "jersey" VARCHAR(255) NOT NULL,
    "member" VARCHAR(255) NOT NULL,
    "face_pic_path" VARCHAR(255) NOT NULL,
    "belong_list" TEXT,
    "height" TEXT,
    "weight" TEXT,
    "position" TEXT,
    "birth" TEXT,
    "age" TEXT,
    "market_value" TEXT,
    "injury" TEXT,
    "versus_team_score_data" TEXT,
    "retire_flg" CHAR(1),
    "deadline" CHAR(1),
    "deadline_contract_date" TEXT,
    "latest_info_date" TEXT,
    "upd_stamp" TEXT,
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "team_member_master_pkey" PRIMARY KEY ("id","team","jersey","member","face_pic_path")
);

-- CreateTable
CREATE TABLE "public"."team_monthly_score_summary" (
    "seq" SERIAL NOT NULL,
    "country" VARCHAR(100),
    "league" VARCHAR(100),
    "team_name" CHAR(100),
    "HA" VARCHAR(1),
    "year" VARCHAR(4),
    "jar_sum_score" CHAR(8),
    "feb_sum_score" CHAR(8),
    "mar_sum_score" CHAR(8),
    "apr_sum_score" CHAR(8),
    "may_sum_score" CHAR(8),
    "jun_sum_score" CHAR(8),
    "jul_sum_score" CHAR(8),
    "aug_sum_score" CHAR(8),
    "sep_sum_score" CHAR(8),
    "oct_sum_score" CHAR(8),
    "nov_sum_score" CHAR(8),
    "dec_sum_score" CHAR(8),
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "team_monthly_score_summary_pkey" PRIMARY KEY ("seq")
);

-- CreateTable
CREATE TABLE "public"."team_time_segment_shooting_stat" (
    "id" SERIAL NOT NULL,
    "data_category" CHAR(100),
    "team_name" CHAR(100),
    "away_team_name" CHAR(100),
    "team_0_10_mean_shoot_count" CHAR(8),
    "team_11_20_mean_shoot_count" CHAR(8),
    "team_21_30_mean_shoot_count" CHAR(8),
    "team_31_40_mean_shoot_count" CHAR(8),
    "team_41_45_mean_shoot_count" CHAR(8),
    "team_46_50_mean_shoot_count" CHAR(8),
    "team_51_60_mean_shoot_count" CHAR(8),
    "team_61_70_mean_shoot_count" CHAR(8),
    "team_71_80_mean_shoot_count" CHAR(8),
    "team_81_90_mean_shoot_count" CHAR(8),
    "team_addi_mean_shoot_count" CHAR(8),
    "team_0_10_mean_shoot_in_count" CHAR(8),
    "team_11_20_mean_shoot_in_count" CHAR(8),
    "team_21_30_mean_shoot_in_count" CHAR(8),
    "team_31_40_mean_shoot_in_count" CHAR(8),
    "team_41_45_mean_shoot_in_count" CHAR(8),
    "team_46_50_mean_shoot_in_count" CHAR(8),
    "team_51_60_mean_shoot_in_count" CHAR(8),
    "team_61_70_mean_shoot_in_count" CHAR(8),
    "team_71_80_mean_shoot_in_count" CHAR(8),
    "team_81_90_mean_shoot_in_count" CHAR(8),
    "team_addi_mean_shoot_in_count" CHAR(8),
    "team_0_10_mean_big_chance_count" CHAR(8),
    "team_11_20_mean_big_chance_count" CHAR(8),
    "team_21_30_mean_big_chance_count" CHAR(8),
    "team_31_40_mean_big_chance_count" CHAR(8),
    "team_41_45_mean_big_chance_count" CHAR(8),
    "team_46_50_mean_big_chance_count" CHAR(8),
    "team_51_60_mean_big_chance_count" CHAR(8),
    "team_61_70_mean_big_chance_count" CHAR(8),
    "team_71_80_mean_big_chance_count" CHAR(8),
    "team_81_90_mean_big_chance_count" CHAR(8),
    "team_addi_mean_big_chance_count" CHAR(8),
    "team_0_10_mean_free_kick_count" CHAR(8),
    "team_11_20_mean_free_kick_count" CHAR(8),
    "team_21_30_mean_free_kick_count" CHAR(8),
    "team_31_40_mean_free_kick_count" CHAR(8),
    "team_41_45_mean_free_kick_count" CHAR(8),
    "team_46_50_mean_free_kick_count" CHAR(8),
    "team_51_60_mean_free_kick_count" CHAR(8),
    "team_61_70_mean_free_kick_count" CHAR(8),
    "team_71_80_mean_free_kick_count" CHAR(8),
    "team_81_90_mean_free_kick_count" CHAR(8),
    "team_addi_mean_free_kick_count" CHAR(8),
    "team_0_10_mean_offside_count" CHAR(8),
    "team_11_20_mean_offside_count" CHAR(8),
    "team_21_30_mean_offside_count" CHAR(8),
    "team_31_40_mean_offside_count" CHAR(8),
    "team_41_45_mean_offside_count" CHAR(8),
    "team_46_50_mean_offside_count" CHAR(8),
    "team_51_60_mean_offside_count" CHAR(8),
    "team_61_70_mean_offside_count" CHAR(8),
    "team_71_80_mean_offside_count" CHAR(8),
    "team_81_90_mean_offside_count" CHAR(8),
    "team_addi_mean_offside_count" CHAR(8),
    "team_0_10_mean_foul_count" CHAR(8),
    "team_11_20_mean_foul_count" CHAR(8),
    "team_21_30_mean_foul_count" CHAR(8),
    "team_31_40_mean_foul_count" CHAR(8),
    "team_41_45_mean_foul_count" CHAR(8),
    "team_46_50_mean_foul_count" CHAR(8),
    "team_51_60_mean_foul_count" CHAR(8),
    "team_61_70_mean_foul_count" CHAR(8),
    "team_71_80_mean_foul_count" CHAR(8),
    "team_81_90_mean_foul_count" CHAR(8),
    "team_addi_mean_foul_count" CHAR(8),
    "team_0_10_mean_yellow_card_count" CHAR(8),
    "team_11_20_mean_yellow_card_count" CHAR(8),
    "team_21_30_mean_yellow_card_count" CHAR(8),
    "team_31_40_mean_yellow_card_count" CHAR(8),
    "team_41_45_mean_yellow_card_count" CHAR(8),
    "team_46_50_mean_yellow_card_count" CHAR(8),
    "team_51_60_mean_yellow_card_count" CHAR(8),
    "team_61_70_mean_yellow_card_count" CHAR(8),
    "team_71_80_mean_yellow_card_count" CHAR(8),
    "team_81_90_mean_yellow_card_count" CHAR(8),
    "team_addi_mean_yellow_card_count" CHAR(8),
    "team_0_10_mean_red_card_count" CHAR(8),
    "team_11_20_mean_red_card_count" CHAR(8),
    "team_21_30_mean_red_card_count" CHAR(8),
    "team_31_40_mean_red_card_count" CHAR(8),
    "team_41_45_mean_red_card_count" CHAR(8),
    "team_46_50_mean_red_card_count" CHAR(8),
    "team_51_60_mean_red_card_count" CHAR(8),
    "team_61_70_mean_red_card_count" CHAR(8),
    "team_71_80_mean_red_card_count" CHAR(8),
    "team_81_90_mean_red_card_count" CHAR(8),
    "team_addi_mean_red_card_count" CHAR(8),
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "team_time_segment_shooting_stat_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."within_data" (
    "id" SERIAL NOT NULL,
    "seq" VARCHAR(10),
    "time_range_feature_id" VARCHAR(3),
    "data_category" CHAR(100),
    "times" CHAR(50),
    "home_rank" CHAR(30),
    "home_team_name" CHAR(100),
    "home_score" CHAR(20) DEFAULT '0',
    "away_rank" CHAR(30),
    "away_team_name" CHAR(100),
    "away_score" CHAR(20) DEFAULT '0',
    "home_exp" CHAR(50),
    "away_exp" CHAR(50),
    "home_donation" CHAR(50),
    "away_donation" CHAR(50),
    "home_shoot_all" CHAR(3),
    "away_shoot_all" CHAR(30),
    "home_shoot_in" CHAR(30),
    "away_shoot_in" CHAR(30),
    "home_shoot_out" CHAR(30),
    "away_shoot_out" CHAR(30),
    "home_block_shoot" CHAR(30),
    "away_block_shoot" CHAR(30),
    "home_big_chance" CHAR(30),
    "away_big_chance" CHAR(30),
    "home_corner" CHAR(30),
    "away_corner" CHAR(30),
    "home_box_shoot_in" CHAR(30),
    "away_box_shoot_in" CHAR(30),
    "home_box_shoot_out" CHAR(30),
    "away_box_shoot_out" CHAR(30),
    "home_goal_post" CHAR(30),
    "away_goal_post" CHAR(30),
    "home_goal_head" CHAR(30),
    "away_goal_head" CHAR(30),
    "home_keeper_save" CHAR(30),
    "away_keeper_save" CHAR(30),
    "home_free_kick" CHAR(30),
    "away_free_kick" CHAR(30),
    "home_offside" CHAR(30),
    "away_offside" CHAR(30),
    "home_foul" CHAR(30),
    "away_foul" CHAR(30),
    "home_yellow_card" CHAR(30),
    "away_yellow_card" CHAR(30),
    "home_red_card" CHAR(30),
    "away_red_card" CHAR(30),
    "home_slow_in" CHAR(30),
    "away_slow_in" CHAR(30),
    "home_box_touch" CHAR(30),
    "away_box_touch" CHAR(30),
    "home_pass_count" CHAR(30),
    "away_pass_count" CHAR(30),
    "home_long_pass_count" CHAR(30),
    "away_long_pass_count" CHAR(30),
    "home_final_third_pass_count" CHAR(30),
    "away_final_third_pass_count" CHAR(30),
    "home_cross_count" CHAR(30),
    "away_cross_count" CHAR(30),
    "home_tackle_count" CHAR(30),
    "away_tackle_count" CHAR(30),
    "home_clear_count" CHAR(30),
    "away_clear_count" CHAR(30),
    "home_duel_count" CHAR(30),
    "away_duel_count" CHAR(30),
    "home_intercept_count" CHAR(30),
    "away_intercept_count" CHAR(30),
    "record_time" TIMESTAMP(0),
    "weather" CHAR(5),
    "temparature" CHAR(10),
    "humid" CHAR(5),
    "judge_member" CHAR(50),
    "home_manager" CHAR(50),
    "away_manager" CHAR(50),
    "home_formation" CHAR(20),
    "away_formation" CHAR(20),
    "studium" CHAR(50),
    "capacity" CHAR(20),
    "audience" CHAR(20),
    "home_max_getting_scorer" CHAR(50),
    "away_max_getting_scorer" CHAR(50),
    "home_max_getting_scorer_game_situation" CHAR(20),
    "away_max_getting_scorer_game_situation" CHAR(20),
    "home_team_home_score" CHAR(20),
    "home_team_home_lost" CHAR(20),
    "away_team_home_score" CHAR(20),
    "away_team_home_lost" CHAR(20),
    "home_team_away_score" CHAR(20),
    "home_team_away_lost" CHAR(20),
    "away_team_away_score" CHAR(20),
    "away_team_away_lost" CHAR(20),
    "notice_flg" CHAR(8),
    "goal_time" CHAR(8),
    "goal_team_member" CHAR(50),
    "judge" CHAR(50),
    "home_team_style" CHAR(50),
    "away_team_style" CHAR(50),
    "probablity" CHAR(50),
    "prediction_score_time" CHAR(50),
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."within_data_20minutes_away_all_league" (
    "id" SERIAL NOT NULL,
    "time_range" VARCHAR(50),
    "feature" VARCHAR(50),
    "threshold" VARCHAR(50),
    "target" VARCHAR(50),
    "search" VARCHAR(50),
    "ratio" VARCHAR(50),
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_20minutes_away_all_league_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."within_data_20minutes_away_scored" (
    "id" SERIAL NOT NULL,
    "country" VARCHAR(50),
    "category" VARCHAR(50),
    "time_range" VARCHAR(50),
    "feature" VARCHAR(50),
    "threshold" VARCHAR(50),
    "target" VARCHAR(50),
    "search" VARCHAR(50),
    "ratio" VARCHAR(50),
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_20minutes_away_scored_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."within_data_20minutes_home_all_league" (
    "id" SERIAL NOT NULL,
    "time_range" VARCHAR(50),
    "feature" VARCHAR(50),
    "threshold" VARCHAR(50),
    "target" VARCHAR(50),
    "search" VARCHAR(50),
    "ratio" VARCHAR(50),
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_20minutes_home_all_league_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."within_data_20minutes_home_scored" (
    "id" SERIAL NOT NULL,
    "country" VARCHAR(50),
    "category" VARCHAR(50),
    "time_range" VARCHAR(50),
    "feature" VARCHAR(50),
    "threshold" VARCHAR(50),
    "target" VARCHAR(50),
    "search" VARCHAR(50),
    "ratio" VARCHAR(50),
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_20minutes_home_scored_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."within_data_20minutes_same_scored" (
    "id" SERIAL NOT NULL,
    "country" VARCHAR(50),
    "category" VARCHAR(50),
    "time_range" VARCHAR(50),
    "feature" VARCHAR(50),
    "threshold" VARCHAR(50),
    "target" VARCHAR(50),
    "search" VARCHAR(50),
    "ratio" VARCHAR(50),
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_20minutes_same_scored_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."within_data_45minutes_away_all_league" (
    "id" SERIAL NOT NULL,
    "time_range" VARCHAR(50),
    "feature" VARCHAR(50),
    "threshold" VARCHAR(50),
    "target" VARCHAR(50),
    "search" VARCHAR(50),
    "ratio" VARCHAR(50),
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_45minutes_away_all_league_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."within_data_45minutes_away_scored" (
    "id" SERIAL NOT NULL,
    "country" VARCHAR(50),
    "category" VARCHAR(50),
    "time_range" VARCHAR(50),
    "feature" VARCHAR(50),
    "threshold" VARCHAR(50),
    "target" VARCHAR(50),
    "search" VARCHAR(50),
    "ratio" VARCHAR(50),
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_45minutes_away_scored_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."within_data_45minutes_home_all_league" (
    "id" SERIAL NOT NULL,
    "time_range" VARCHAR(50),
    "feature" VARCHAR(50),
    "threshold" VARCHAR(50),
    "target" VARCHAR(50),
    "search" VARCHAR(50),
    "ratio" VARCHAR(50),
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_45minutes_home_all_league_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."within_data_45minutes_home_scored" (
    "id" SERIAL NOT NULL,
    "country" VARCHAR(50),
    "category" VARCHAR(50),
    "time_range" VARCHAR(50),
    "feature" VARCHAR(50),
    "threshold" VARCHAR(50),
    "target" VARCHAR(50),
    "search" VARCHAR(50),
    "ratio" VARCHAR(50),
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_45minutes_home_scored_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "country_UNIQUE" ON "public"."country_league_summary"("country");

-- CreateIndex
CREATE UNIQUE INDEX "league_UNIQUE" ON "public"."country_league_summary"("league");

-- CreateIndex
CREATE INDEX "idx_data_keys_times_seq" ON "public"."data"("data_category", "home_team_name", "away_team_name", "times", "seq");

-- CreateIndex
CREATE INDEX "idx_lookup" ON "public"."surface_overview"("country", "league", "game_year", "game_month", "team");

-- CreateIndex
CREATE UNIQUE INDEX "uk_team_month" ON "public"."surface_overview"("country", "league", "team", "game_year", "game_month");
