-- CreateTable
CREATE TABLE "average_statistics_csv_tmp_data" (
    "id" INTEGER NOT NULL,
    "score" TEXT,
    "country" TEXT,
    "league" TEXT,
    "team" TEXT,
    "game_count" TEXT,
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "average_statistics_csv_tmp_data_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "average_statistics_team_detail_data" (
    "id" INTEGER NOT NULL,
    "situation" TEXT,
    "team" TEXT,
    "opposite_team" TEXT,
    "ha" VARCHAR(1),
    "country" TEXT,
    "league" TEXT,
    "exp_stat" TEXT,
    "donation_stat" TEXT,
    "shoot_all_stat" TEXT,
    "shoot_in_stat" TEXT,
    "shoot_out_stat" TEXT,
    "block_shoot_stat" TEXT,
    "big_chance_stat" TEXT,
    "corner_stat" TEXT,
    "box_shoot_in_stat" TEXT,
    "box_shoot_out_stat" TEXT,
    "goal_post_stat" TEXT,
    "goal_head_stat" TEXT,
    "keeper_save_stat" TEXT,
    "free_kick_stat" TEXT,
    "offside_stat" TEXT,
    "foul_stat" TEXT,
    "yellow_card_stat" TEXT,
    "red_card_stat" TEXT,
    "slow_in_stat" TEXT,
    "box_touch_stat" TEXT,
    "pass_count_stat" TEXT,
    "final_third_pass_count_stat" TEXT,
    "cross_count_stat" TEXT,
    "tackle_count_stat" TEXT,
    "clear_count_stat" TEXT,
    "intercept_count_stat" TEXT,
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "average_statistics_team_detail_data_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "calc_correlation" (
    "id" SERIAL NOT NULL,
    "file" TEXT,
    "country" TEXT,
    "league" TEXT,
    "home" TEXT,
    "away" TEXT,
    "score" TEXT,
    "chk_body" TEXT,
    "home_exp_info" TEXT,
    "away_exp_info" TEXT,
    "home_in_goal_exp_info" TEXT,
    "away_in_goal_exp_info" TEXT,
    "home_donation_info" TEXT,
    "away_donation_info" TEXT,
    "home_shoot_all_info" TEXT,
    "away_shoot_all_info" TEXT,
    "home_shoot_in_info" TEXT,
    "away_shoot_in_info" TEXT,
    "home_shoot_out_info" TEXT,
    "away_shoot_out_info" TEXT,
    "home_block_shoot_info" TEXT,
    "away_block_shoot_info" TEXT,
    "home_big_chance_info" TEXT,
    "away_big_chance_info" TEXT,
    "home_corner_info" TEXT,
    "away_corner_info" TEXT,
    "home_box_shoot_in_info" TEXT,
    "away_box_shoot_in_info" TEXT,
    "home_box_shoot_out_info" TEXT,
    "away_box_shoot_out_info" TEXT,
    "home_goal_post_info" TEXT,
    "away_goal_post_info" TEXT,
    "home_goal_head_info" TEXT,
    "away_goal_head_info" TEXT,
    "home_keeper_save_info" TEXT,
    "away_keeper_save_info" TEXT,
    "home_free_kick_info" TEXT,
    "away_free_kick_info" TEXT,
    "home_offside_info" TEXT,
    "away_offside_info" TEXT,
    "home_foul_info" TEXT,
    "away_foul_info" TEXT,
    "home_yellow_card_info" TEXT,
    "away_yellow_card_info" TEXT,
    "home_red_card_info" TEXT,
    "away_red_card_info" TEXT,
    "home_slow_in_info" TEXT,
    "away_slow_in_info" TEXT,
    "home_box_touch_info" TEXT,
    "away_box_touch_info" TEXT,
    "home_pass_count_info_on_success_ratio" TEXT,
    "home_pass_count_info_on_success_count" TEXT,
    "home_pass_count_info_on_try_count" TEXT,
    "away_pass_count_info_on_success_ratio" TEXT,
    "away_pass_count_info_on_success_count" TEXT,
    "away_pass_count_info_on_try_count" TEXT,
    "home_final_third_pass_count_info_on_success_ratio" TEXT,
    "home_final_third_pass_count_info_on_success_count" TEXT,
    "home_final_third_pass_count_info_on_try_count" TEXT,
    "away_final_third_pass_count_info_on_success_ratio" TEXT,
    "away_final_third_pass_count_info_on_success_count" TEXT,
    "away_final_third_pass_count_info_on_try_count" TEXT,
    "home_cross_count_info_on_success_ratio" TEXT,
    "home_cross_count_info_on_success_count" TEXT,
    "home_cross_count_info_on_try_count" TEXT,
    "away_cross_count_info_on_success_ratio" TEXT,
    "away_cross_count_info_on_success_count" TEXT,
    "away_cross_count_info_on_try_count" TEXT,
    "home_tackle_count_info_on_success_ratio" TEXT,
    "home_tackle_count_info_on_success_count" TEXT,
    "home_tackle_count_info_on_try_count" TEXT,
    "away_tackle_count_info_on_success_ratio" TEXT,
    "away_tackle_count_info_on_success_count" TEXT,
    "away_tackle_count_info_on_try_count" TEXT,
    "home_clear_count_info" TEXT,
    "away_clear_count_info" TEXT,
    "home_intercept_count_info" TEXT,
    "away_intercept_count_info" TEXT,
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "calc_correlation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "calc_correlation_ranking" (
    "id" SERIAL NOT NULL,
    "country" TEXT,
    "league" TEXT,
    "home" TEXT,
    "away" TEXT,
    "score" TEXT,
    "chk_body" TEXT,
    "rank_1th" TEXT,
    "rank_2th" TEXT,
    "rank_3th" TEXT,
    "rank_4th" TEXT,
    "rank_5th" TEXT,
    "rank_6th" TEXT,
    "rank_7th" TEXT,
    "rank_8th" TEXT,
    "rank_9th" TEXT,
    "rank_10th" TEXT,
    "rank_11th" TEXT,
    "rank_12th" TEXT,
    "rank_13th" TEXT,
    "rank_14th" TEXT,
    "rank_15th" TEXT,
    "rank_16th" TEXT,
    "rank_17th" TEXT,
    "rank_18th" TEXT,
    "rank_19th" TEXT,
    "rank_20th" TEXT,
    "rank_21th" TEXT,
    "rank_22th" TEXT,
    "rank_23th" TEXT,
    "rank_24th" TEXT,
    "rank_25th" TEXT,
    "rank_26th" TEXT,
    "rank_27th" TEXT,
    "rank_28th" TEXT,
    "rank_29th" TEXT,
    "rank_30th" TEXT,
    "rank_31th" TEXT,
    "rank_32th" TEXT,
    "rank_33th" TEXT,
    "rank_34th" TEXT,
    "rank_35th" TEXT,
    "rank_36th" TEXT,
    "rank_37th" TEXT,
    "rank_38th" TEXT,
    "rank_39th" TEXT,
    "rank_40th" TEXT,
    "rank_41th" TEXT,
    "rank_42th" TEXT,
    "rank_43th" TEXT,
    "rank_44th" TEXT,
    "rank_45th" TEXT,
    "rank_46th" TEXT,
    "rank_47th" TEXT,
    "rank_48th" TEXT,
    "rank_49th" TEXT,
    "rank_50th" TEXT,
    "rank_51th" TEXT,
    "rank_52th" TEXT,
    "rank_53th" TEXT,
    "rank_54th" TEXT,
    "rank_55th" TEXT,
    "rank_56th" TEXT,
    "rank_57th" TEXT,
    "rank_58th" TEXT,
    "rank_59th" TEXT,
    "rank_60th" TEXT,
    "rank_61th" TEXT,
    "rank_62th" TEXT,
    "rank_63th" TEXT,
    "rank_64th" TEXT,
    "rank_65th" TEXT,
    "rank_66th" TEXT,
    "rank_67th" TEXT,
    "rank_68th" TEXT,
    "rank_69th" TEXT,
    "rank_70th" TEXT,
    "rank_71th" TEXT,
    "rank_72th" TEXT,
    "rank_73th" TEXT,
    "rank_74th" TEXT,
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "calc_correlation_ranking_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "condition_result_data" (
    "data_seq" SERIAL NOT NULL,
    "mail_target_count" TEXT,
    "mail_anonymous_target_count" TEXT,
    "mail_target_success_count" TEXT,
    "mail_target_fail_count" TEXT,
    "ex_mail_target_to_no_result_count" TEXT,
    "ex_no_fin_data_to_no_result_count" TEXT,
    "goal_delete" TEXT,
    "alter_target_mail_anonymous" TEXT,
    "alter_target_mail_fail" TEXT,
    "no_result_count" TEXT,
    "err_data" TEXT,
    "condition_data" BYTEA NOT NULL,
    "hash" TEXT,
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "condition_result_data_pkey" PRIMARY KEY ("data_seq")
);

-- CreateTable
CREATE TABLE "country_league_master" (
    "id" SERIAL NOT NULL,
    "country" TEXT NOT NULL,
    "league" TEXT NOT NULL,
    "team" TEXT NOT NULL,
    "link" TEXT NOT NULL,
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "country_league_master_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "country_league_season_master" (
    "id" SERIAL NOT NULL,
    "country" TEXT NOT NULL,
    "league" TEXT NOT NULL,
    "start_season_date" TIMESTAMPTZ(0),
    "end_season_date" TIMESTAMPTZ(0),
    "round" VARCHAR(2),
    "path" TEXT,
    "disp_valid_flg" VARCHAR(1) NOT NULL DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "country_league_season_master_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "country_league_summary" (
    "id" SERIAL NOT NULL,
    "country" TEXT NOT NULL,
    "league" TEXT NOT NULL,
    "data_count" TEXT NOT NULL,
    "csv_count" TEXT NOT NULL,
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "country_league_summary_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "data" (
    "seq" SERIAL NOT NULL,
    "condition_result_data_seq_id" VARCHAR(3),
    "data_category" TEXT,
    "times" TEXT,
    "home_rank" TEXT,
    "home_team_name" TEXT,
    "home_score" TEXT DEFAULT '0',
    "away_rank" TEXT,
    "away_team_name" TEXT,
    "away_score" TEXT DEFAULT '0',
    "home_exp" TEXT,
    "away_exp" TEXT,
    "home_in_goal_exp" TEXT,
    "away_in_goal_exp" TEXT,
    "home_donation" TEXT,
    "away_donation" TEXT,
    "home_shoot_all" TEXT,
    "away_shoot_all" TEXT,
    "home_shoot_in" TEXT,
    "away_shoot_in" TEXT,
    "home_shoot_out" TEXT,
    "away_shoot_out" TEXT,
    "home_block_shoot" TEXT,
    "away_block_shoot" TEXT,
    "home_big_chance" TEXT,
    "away_big_chance" TEXT,
    "home_corner" TEXT,
    "away_corner" TEXT,
    "home_box_shoot_in" TEXT,
    "away_box_shoot_in" TEXT,
    "home_box_shoot_out" TEXT,
    "away_box_shoot_out" TEXT,
    "home_goal_post" TEXT,
    "away_goal_post" TEXT,
    "home_goal_head" TEXT,
    "away_goal_head" TEXT,
    "home_keeper_save" TEXT,
    "away_keeper_save" TEXT,
    "home_free_kick" TEXT,
    "away_free_kick" TEXT,
    "home_offside" TEXT,
    "away_offside" TEXT,
    "home_foul" TEXT,
    "away_foul" TEXT,
    "home_yellow_card" TEXT,
    "away_yellow_card" TEXT,
    "home_red_card" TEXT,
    "away_red_card" TEXT,
    "home_slow_in" TEXT,
    "away_slow_in" TEXT,
    "home_box_touch" TEXT,
    "away_box_touch" TEXT,
    "home_pass_count" TEXT,
    "away_pass_count" TEXT,
    "home_long_pass_count" TEXT,
    "away_long_pass_count" TEXT,
    "home_final_third_pass_count" TEXT,
    "away_final_third_pass_count" TEXT,
    "home_cross_count" TEXT,
    "away_cross_count" TEXT,
    "home_tackle_count" TEXT,
    "away_tackle_count" TEXT,
    "home_clear_count" TEXT,
    "away_clear_count" TEXT,
    "home_duel_count" TEXT,
    "away_duel_count" TEXT,
    "home_intercept_count" TEXT,
    "away_intercept_count" TEXT,
    "record_time" TIMESTAMPTZ(0),
    "weather" TEXT,
    "temparature" TEXT,
    "humid" TEXT,
    "judge_member" TEXT,
    "home_manager" TEXT,
    "away_manager" TEXT,
    "home_formation" TEXT,
    "away_formation" TEXT,
    "studium" TEXT,
    "capacity" TEXT,
    "audience" TEXT,
    "location" TEXT,
    "home_max_getting_scorer" TEXT,
    "away_max_getting_scorer" TEXT,
    "home_max_getting_scorer_game_situation" TEXT,
    "away_max_getting_scorer_game_situation" TEXT,
    "home_team_home_score" TEXT,
    "home_team_home_lost" TEXT,
    "away_team_home_score" TEXT,
    "away_team_home_lost" TEXT,
    "home_team_away_score" TEXT,
    "home_team_away_lost" TEXT,
    "away_team_away_score" TEXT,
    "away_team_away_lost" TEXT,
    "notice_flg" TEXT,
    "game_link" TEXT,
    "goal_time" TEXT,
    "goal_team_member" TEXT,
    "judge" TEXT,
    "home_team_style" TEXT,
    "away_team_style" TEXT,
    "probablity" TEXT,
    "prediction_score_time" TEXT,
    "game_id" TEXT,
    "match_id" TEXT,
    "time_sort_seconds" TEXT,
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "data_pkey" PRIMARY KEY ("seq")
);

-- CreateTable
CREATE TABLE "each_team_score_based_feature_stats" (
    "id" SERIAL NOT NULL,
    "situation" TEXT,
    "score" TEXT,
    "country" TEXT,
    "league" TEXT,
    "team" TEXT,
    "home_exp_stat" TEXT,
    "away_exp_stat" TEXT,
    "home_in_goal_exp_stat" TEXT,
    "away_in_goal_exp_stat" TEXT,
    "home_donation_stat" TEXT,
    "away_donation_stat" TEXT,
    "home_shoot_all_stat" TEXT,
    "away_shoot_all_stat" TEXT,
    "home_shoot_in_stat" TEXT,
    "away_shoot_in_stat" TEXT,
    "home_shoot_out_stat" TEXT,
    "away_shoot_out_stat" TEXT,
    "home_block_shoot_stat" TEXT,
    "away_block_shoot_stat" TEXT,
    "home_big_chance_stat" TEXT,
    "away_big_chance_stat" TEXT,
    "home_corner_stat" TEXT,
    "away_corner_stat" TEXT,
    "home_box_shoot_in_stat" TEXT,
    "away_box_shoot_in_stat" TEXT,
    "home_box_shoot_out_stat" TEXT,
    "away_box_shoot_out_stat" TEXT,
    "home_goal_post_stat" TEXT,
    "away_goal_post_stat" TEXT,
    "home_goal_head_stat" TEXT,
    "away_goal_head_stat" TEXT,
    "home_keeper_save_stat" TEXT,
    "away_keeper_save_stat" TEXT,
    "home_free_kick_stat" TEXT,
    "away_free_kick_stat" TEXT,
    "home_offside_stat" TEXT,
    "away_offside_stat" TEXT,
    "home_foul_stat" TEXT,
    "away_foul_stat" TEXT,
    "home_yellow_card_stat" TEXT,
    "away_yellow_card_stat" TEXT,
    "home_red_card_stat" TEXT,
    "away_red_card_stat" TEXT,
    "home_slow_in_stat" TEXT,
    "away_slow_in_stat" TEXT,
    "home_box_touch_stat" TEXT,
    "away_box_touch_stat" TEXT,
    "home_pass_count_stat" TEXT,
    "away_pass_count_stat" TEXT,
    "home_long_pass_count_stat" TEXT,
    "away_long_pass_count_stat" TEXT,
    "home_final_third_pass_count_stat" TEXT,
    "away_final_third_pass_count_stat" TEXT,
    "home_cross_count_stat" TEXT,
    "away_cross_count_stat" TEXT,
    "home_tackle_count_stat" TEXT,
    "away_tackle_count_stat" TEXT,
    "home_clear_count_stat" TEXT,
    "away_clear_count_stat" TEXT,
    "home_duel_count_stat" TEXT,
    "away_duel_count_stat" TEXT,
    "home_intercept_count_stat" TEXT,
    "away_intercept_count_stat" TEXT,
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "each_team_score_based_feature_stats_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "each_team_score_based_feature_stats_history" (
    "id" SERIAL NOT NULL,
    "situation" TEXT,
    "score" TEXT,
    "country" TEXT,
    "league" TEXT,
    "team" TEXT,
    "home_exp_stat" TEXT,
    "away_exp_stat" TEXT,
    "home_in_goal_exp_stat" TEXT,
    "away_in_goal_exp_stat" TEXT,
    "home_donation_stat" TEXT,
    "away_donation_stat" TEXT,
    "home_shoot_all_stat" TEXT,
    "away_shoot_all_stat" TEXT,
    "home_shoot_in_stat" TEXT,
    "away_shoot_in_stat" TEXT,
    "home_shoot_out_stat" TEXT,
    "away_shoot_out_stat" TEXT,
    "home_block_shoot_stat" TEXT,
    "away_block_shoot_stat" TEXT,
    "home_big_chance_stat" TEXT,
    "away_big_chance_stat" TEXT,
    "home_corner_stat" TEXT,
    "away_corner_stat" TEXT,
    "home_box_shoot_in_stat" TEXT,
    "away_box_shoot_in_stat" TEXT,
    "home_box_shoot_out_stat" TEXT,
    "away_box_shoot_out_stat" TEXT,
    "home_goal_post_stat" TEXT,
    "away_goal_post_stat" TEXT,
    "home_goal_head_stat" TEXT,
    "away_goal_head_stat" TEXT,
    "home_keeper_save_stat" TEXT,
    "away_keeper_save_stat" TEXT,
    "home_free_kick_stat" TEXT,
    "away_free_kick_stat" TEXT,
    "home_offside_stat" TEXT,
    "away_offside_stat" TEXT,
    "home_foul_stat" TEXT,
    "away_foul_stat" TEXT,
    "home_yellow_card_stat" TEXT,
    "away_yellow_card_stat" TEXT,
    "home_red_card_stat" TEXT,
    "away_red_card_stat" TEXT,
    "home_slow_in_stat" TEXT,
    "away_slow_in_stat" TEXT,
    "home_box_touch_stat" TEXT,
    "away_box_touch_stat" TEXT,
    "home_pass_count_stat" TEXT,
    "away_pass_count_stat" TEXT,
    "home_long_pass_count_stat" TEXT,
    "away_long_pass_count_stat" TEXT,
    "home_final_third_pass_count_stat" TEXT,
    "away_final_third_pass_count_stat" TEXT,
    "home_cross_count_stat" TEXT,
    "away_cross_count_stat" TEXT,
    "home_tackle_count_stat" TEXT,
    "away_tackle_count_stat" TEXT,
    "home_clear_count_stat" TEXT,
    "away_clear_count_stat" TEXT,
    "home_duel_count_stat" TEXT,
    "away_duel_count_stat" TEXT,
    "home_intercept_count_stat" TEXT,
    "away_intercept_count_stat" TEXT,
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "each_team_score_based_feature_stats_history_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "future_master" (
    "seq" BIGSERIAL NOT NULL,
    "game_team_category" TEXT NOT NULL,
    "future_time" TIMESTAMPTZ(0) NOT NULL,
    "home_rank" TEXT,
    "away_rank" TEXT,
    "home_team_name" TEXT,
    "away_team_name" TEXT,
    "home_max_getting_scorer" TEXT,
    "away_max_getting_scorer" TEXT,
    "home_team_home_score" TEXT,
    "home_team_home_lost" TEXT,
    "away_team_home_score" TEXT,
    "away_team_home_lost" TEXT,
    "home_team_away_score" TEXT,
    "home_team_away_lost" TEXT,
    "away_team_away_score" TEXT,
    "away_team_away_lost" TEXT,
    "game_link" TEXT,
    "data_time" TIMESTAMPTZ(0),
    "start_flg" VARCHAR(1) NOT NULL DEFAULT '0',
    "register_id" TEXT,
    "register_time" TIMESTAMPTZ(0),
    "update_id" TEXT,
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "future_master_pkey" PRIMARY KEY ("seq")
);

-- CreateTable
CREATE TABLE "league_score_time_band_stats" (
    "id" SERIAL NOT NULL,
    "country" TEXT,
    "league" TEXT,
    "sum_score_value" TEXT,
    "time_range_area" TEXT,
    "target" TEXT,
    "search" TEXT,
    "ratio" TEXT,
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "league_score_time_band_stats_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "league_score_time_band_stats_split_score" (
    "id" SERIAL NOT NULL,
    "country" TEXT,
    "league" TEXT,
    "home_score_value" TEXT,
    "away_score_value" TEXT,
    "home_time_range_area" TEXT,
    "away_time_range_area" TEXT,
    "target" TEXT,
    "search" TEXT,
    "ratio" TEXT,
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "league_score_time_band_stats_split_score_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "match_classification_result" (
    "id" SERIAL NOT NULL,
    "classify_mode" VARCHAR(2),
    "data_category" TEXT,
    "times" TEXT,
    "home_rank" TEXT,
    "home_team_name" TEXT,
    "home_score" TEXT DEFAULT '0',
    "away_rank" TEXT,
    "away_team_name" TEXT,
    "away_score" TEXT DEFAULT '0',
    "home_exp" TEXT,
    "away_exp" TEXT,
    "home_in_goal_exp" TEXT,
    "away_in_goal_exp" TEXT,
    "home_donation" TEXT,
    "away_donation" TEXT,
    "home_shoot_all" TEXT,
    "away_shoot_all" TEXT,
    "home_shoot_in" TEXT,
    "away_shoot_in" TEXT,
    "home_shoot_out" TEXT,
    "away_shoot_out" TEXT,
    "home_block_shoot" TEXT,
    "away_block_shoot" TEXT,
    "home_big_chance" TEXT,
    "away_big_chance" TEXT,
    "home_corner" TEXT,
    "away_corner" TEXT,
    "home_box_shoot_in" TEXT,
    "away_box_shoot_in" TEXT,
    "home_box_shoot_out" TEXT,
    "away_box_shoot_out" TEXT,
    "home_goal_post" TEXT,
    "away_goal_post" TEXT,
    "home_goal_head" TEXT,
    "away_goal_head" TEXT,
    "home_keeper_save" TEXT,
    "away_keeper_save" TEXT,
    "home_free_kick" TEXT,
    "away_free_kick" TEXT,
    "home_offside" TEXT,
    "away_offside" TEXT,
    "home_foul" TEXT,
    "away_foul" TEXT,
    "home_yellow_card" TEXT,
    "away_yellow_card" TEXT,
    "home_red_card" TEXT,
    "away_red_card" TEXT,
    "home_slow_in" TEXT,
    "away_slow_in" TEXT,
    "home_box_touch" TEXT,
    "away_box_touch" TEXT,
    "home_pass_count" TEXT,
    "away_pass_count" TEXT,
    "home_final_third_pass_count" TEXT,
    "away_final_third_pass_count" TEXT,
    "home_cross_count" TEXT,
    "away_cross_count" TEXT,
    "home_tackle_count" TEXT,
    "away_tackle_count" TEXT,
    "home_clear_count" TEXT,
    "away_clear_count" TEXT,
    "home_intercept_count" TEXT,
    "away_intercept_count" TEXT,
    "record_time" TIMESTAMPTZ(0),
    "weather" TEXT,
    "temparature" TEXT,
    "humid" TEXT,
    "judge_member" TEXT,
    "home_manager" TEXT,
    "away_manager" TEXT,
    "home_formation" TEXT,
    "away_formation" TEXT,
    "studium" TEXT,
    "capacity" TEXT,
    "audience" TEXT,
    "home_max_getting_scorer" TEXT,
    "away_max_getting_scorer" TEXT,
    "home_max_getting_scorer_game_situation" TEXT,
    "away_max_getting_scorer_game_situation" TEXT,
    "home_team_home_score" TEXT,
    "home_team_home_lost" TEXT,
    "away_team_home_score" TEXT,
    "away_team_home_lost" TEXT,
    "home_team_away_score" TEXT,
    "home_team_away_lost" TEXT,
    "away_team_away_score" TEXT,
    "away_team_away_lost" TEXT,
    "notice_flg" TEXT,
    "goal_time" TEXT,
    "goal_team_member" TEXT,
    "judge" TEXT,
    "home_team_style" TEXT,
    "away_team_style" TEXT,
    "probablity" TEXT,
    "prediction_score_time" TEXT,
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "match_classification_result_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "match_classification_result_count" (
    "id" SERIAL NOT NULL,
    "country" TEXT,
    "league" TEXT,
    "classify_mode" VARCHAR(2),
    "count" TEXT,
    "remarks" VARCHAR(3000),
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "match_classification_result_count_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "no_goal_match_stats" (
    "id" SERIAL NOT NULL,
    "seq" TEXT,
    "data_category" TEXT,
    "times" TEXT,
    "home_rank" TEXT,
    "home_team_name" TEXT,
    "home_score" TEXT DEFAULT '0',
    "away_rank" TEXT,
    "away_team_name" TEXT,
    "away_score" TEXT DEFAULT '0',
    "home_exp" TEXT,
    "away_exp" TEXT,
    "home_in_goal_exp" TEXT,
    "away_in_goal_exp" TEXT,
    "home_donation" TEXT,
    "away_donation" TEXT,
    "home_shoot_all" TEXT,
    "away_shoot_all" TEXT,
    "home_shoot_in" TEXT,
    "away_shoot_in" TEXT,
    "home_shoot_out" TEXT,
    "away_shoot_out" TEXT,
    "home_block_shoot" TEXT,
    "away_block_shoot" TEXT,
    "home_big_chance" TEXT,
    "away_big_chance" TEXT,
    "home_corner" TEXT,
    "away_corner" TEXT,
    "home_box_shoot_in" TEXT,
    "away_box_shoot_in" TEXT,
    "home_box_shoot_out" TEXT,
    "away_box_shoot_out" TEXT,
    "home_goal_post" TEXT,
    "away_goal_post" TEXT,
    "home_goal_head" TEXT,
    "away_goal_head" TEXT,
    "home_keeper_save" TEXT,
    "away_keeper_save" TEXT,
    "home_free_kick" TEXT,
    "away_free_kick" TEXT,
    "home_offside" TEXT,
    "away_offside" TEXT,
    "home_foul" TEXT,
    "away_foul" TEXT,
    "home_yellow_card" TEXT,
    "away_yellow_card" TEXT,
    "home_red_card" TEXT,
    "away_red_card" TEXT,
    "home_slow_in" TEXT,
    "away_slow_in" TEXT,
    "home_box_touch" TEXT,
    "away_box_touch" TEXT,
    "home_pass_count" TEXT,
    "away_pass_count" TEXT,
    "home_long_pass_count" TEXT,
    "away_long_pass_count" TEXT,
    "home_final_third_pass_count" TEXT,
    "away_final_third_pass_count" TEXT,
    "home_cross_count" TEXT,
    "away_cross_count" TEXT,
    "home_tackle_count" TEXT,
    "away_tackle_count" TEXT,
    "home_clear_count" TEXT,
    "away_clear_count" TEXT,
    "home_duel_count" TEXT,
    "away_duel_count" TEXT,
    "home_intercept_count" TEXT,
    "away_intercept_count" TEXT,
    "record_time" TIMESTAMPTZ(0),
    "weather" TEXT,
    "temparature" TEXT,
    "humid" TEXT,
    "judge_member" TEXT,
    "home_manager" TEXT,
    "away_manager" TEXT,
    "home_formation" TEXT,
    "away_formation" TEXT,
    "studium" TEXT,
    "capacity" TEXT,
    "audience" TEXT,
    "home_max_getting_scorer" TEXT,
    "away_max_getting_scorer" TEXT,
    "home_max_getting_scorer_game_situation" TEXT,
    "away_max_getting_scorer_game_situation" TEXT,
    "home_team_home_score" TEXT,
    "home_team_home_lost" TEXT,
    "away_team_home_score" TEXT,
    "away_team_home_lost" TEXT,
    "home_team_away_score" TEXT,
    "home_team_away_lost" TEXT,
    "away_team_away_score" TEXT,
    "away_team_away_lost" TEXT,
    "notice_flg" TEXT,
    "goal_time" TEXT,
    "goal_team_member" TEXT,
    "judge" TEXT,
    "home_team_style" TEXT,
    "away_team_style" TEXT,
    "probablity" TEXT,
    "prediction_score_time" TEXT,
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "no_goal_match_stats_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "score_based_feature_stats" (
    "id" SERIAL NOT NULL,
    "situation" TEXT,
    "score" TEXT,
    "country" TEXT,
    "league" TEXT,
    "home_exp_stat" TEXT,
    "away_exp_stat" TEXT,
    "home_in_goal_exp_stat" TEXT,
    "away_in_goal_exp_stat" TEXT,
    "home_donation_stat" TEXT,
    "away_donation_stat" TEXT,
    "home_shoot_all_stat" TEXT,
    "away_shoot_all_stat" TEXT,
    "home_shoot_in_stat" TEXT,
    "away_shoot_in_stat" TEXT,
    "home_shoot_out_stat" TEXT,
    "away_shoot_out_stat" TEXT,
    "home_block_shoot_stat" TEXT,
    "away_block_shoot_stat" TEXT,
    "home_big_chance_stat" TEXT,
    "away_big_chance_stat" TEXT,
    "home_corner_stat" TEXT,
    "away_corner_stat" TEXT,
    "home_box_shoot_in_stat" TEXT,
    "away_box_shoot_in_stat" TEXT,
    "home_box_shoot_out_stat" TEXT,
    "away_box_shoot_out_stat" TEXT,
    "home_goal_post_stat" TEXT,
    "away_goal_post_stat" TEXT,
    "home_goal_head_stat" TEXT,
    "away_goal_head_stat" TEXT,
    "home_keeper_save_stat" TEXT,
    "away_keeper_save_stat" TEXT,
    "home_free_kick_stat" TEXT,
    "away_free_kick_stat" TEXT,
    "home_offside_stat" TEXT,
    "away_offside_stat" TEXT,
    "home_foul_stat" TEXT,
    "away_foul_stat" TEXT,
    "home_yellow_card_stat" TEXT,
    "away_yellow_card_stat" TEXT,
    "home_red_card_stat" TEXT,
    "away_red_card_stat" TEXT,
    "home_slow_in_stat" TEXT,
    "away_slow_in_stat" TEXT,
    "home_box_touch_stat" TEXT,
    "away_box_touch_stat" TEXT,
    "home_pass_count_stat" TEXT,
    "away_pass_count_stat" TEXT,
    "home_long_pass_count_stat" TEXT,
    "away_long_pass_count_stat" TEXT,
    "home_final_third_pass_count_stat" TEXT,
    "away_final_third_pass_count_stat" TEXT,
    "home_cross_count_stat" TEXT,
    "away_cross_count_stat" TEXT,
    "home_tackle_count_stat" TEXT,
    "away_tackle_count_stat" TEXT,
    "home_clear_count_stat" TEXT,
    "away_clear_count_stat" TEXT,
    "home_duel_count_stat" TEXT,
    "away_duel_count_stat" TEXT,
    "home_intercept_count_stat" TEXT,
    "away_intercept_count_stat" TEXT,
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "score_based_feature_stats_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "score_based_feature_stats_history" (
    "id" SERIAL NOT NULL,
    "situation" TEXT,
    "score" TEXT,
    "country" TEXT,
    "league" TEXT,
    "home_exp_stat" TEXT,
    "away_exp_stat" TEXT,
    "home_in_goal_exp_stat" TEXT,
    "away_in_goal_exp_stat" TEXT,
    "home_donation_stat" TEXT,
    "away_donation_stat" TEXT,
    "home_shoot_all_stat" TEXT,
    "away_shoot_all_stat" TEXT,
    "home_shoot_in_stat" TEXT,
    "away_shoot_in_stat" TEXT,
    "home_shoot_out_stat" TEXT,
    "away_shoot_out_stat" TEXT,
    "home_block_shoot_stat" TEXT,
    "away_block_shoot_stat" TEXT,
    "home_big_chance_stat" TEXT,
    "away_big_chance_stat" TEXT,
    "home_corner_stat" TEXT,
    "away_corner_stat" TEXT,
    "home_box_shoot_in_stat" TEXT,
    "away_box_shoot_in_stat" TEXT,
    "home_box_shoot_out_stat" TEXT,
    "away_box_shoot_out_stat" TEXT,
    "home_goal_post_stat" TEXT,
    "away_goal_post_stat" TEXT,
    "home_goal_head_stat" TEXT,
    "away_goal_head_stat" TEXT,
    "home_keeper_save_stat" TEXT,
    "away_keeper_save_stat" TEXT,
    "home_free_kick_stat" TEXT,
    "away_free_kick_stat" TEXT,
    "home_offside_stat" TEXT,
    "away_offside_stat" TEXT,
    "home_foul_stat" TEXT,
    "away_foul_stat" TEXT,
    "home_yellow_card_stat" TEXT,
    "away_yellow_card_stat" TEXT,
    "home_red_card_stat" TEXT,
    "away_red_card_stat" TEXT,
    "home_slow_in_stat" TEXT,
    "away_slow_in_stat" TEXT,
    "home_box_touch_stat" TEXT,
    "away_box_touch_stat" TEXT,
    "home_pass_count_stat" TEXT,
    "away_pass_count_stat" TEXT,
    "home_long_pass_count_stat" TEXT,
    "away_long_pass_count_stat" TEXT,
    "home_final_third_pass_count_stat" TEXT,
    "away_final_third_pass_count_stat" TEXT,
    "home_cross_count_stat" TEXT,
    "away_cross_count_stat" TEXT,
    "home_tackle_count_stat" TEXT,
    "away_tackle_count_stat" TEXT,
    "home_clear_count_stat" TEXT,
    "away_clear_count_stat" TEXT,
    "home_duel_count_stat" TEXT,
    "away_duel_count_stat" TEXT,
    "home_intercept_count_stat" TEXT,
    "away_intercept_count_stat" TEXT,
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "score_based_feature_stats_history_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "scoring_playstyle_past_data" (
    "id" INTEGER NOT NULL,
    "data_category" TEXT,
    "home_team_name" TEXT,
    "away_team_name" TEXT,
    "diff_home_score" TEXT,
    "diff_away_score" TEXT,
    "diff_home_donation" TEXT,
    "diff_away_donation" TEXT,
    "diff_home_shoot_all" TEXT,
    "diff_away_shoot_all" TEXT,
    "diff_home_shoot_in" TEXT,
    "diff_away_shoot_in" TEXT,
    "diff_home_shoot_out" TEXT,
    "diff_away_shoot_out" TEXT,
    "diff_home_block_shoot" TEXT,
    "diff_away_block_shoot" TEXT,
    "diff_home_big_chance" TEXT,
    "diff_away_big_chance" TEXT,
    "diff_home_corner" TEXT,
    "diff_away_corner" TEXT,
    "diff_home_box_shoot_in" TEXT,
    "diff_away_box_shoot_in" TEXT,
    "diff_home_box_shoot_out" TEXT,
    "diff_away_box_shoot_out" TEXT,
    "diff_home_goal_post" TEXT,
    "diff_away_goal_post" TEXT,
    "diff_home_goal_head" TEXT,
    "diff_away_goal_head" TEXT,
    "diff_home_keeper_save" TEXT,
    "diff_away_keeper_save" TEXT,
    "diff_home_free_kick" TEXT,
    "diff_away_free_kick" TEXT,
    "diff_home_offside" TEXT,
    "diff_away_offside" TEXT,
    "diff_home_foul" TEXT,
    "diff_away_foul" TEXT,
    "diff_home_yellow_card" TEXT,
    "diff_away_yellow_card" TEXT,
    "diff_home_red_card" TEXT,
    "diff_away_red_card" TEXT,
    "diff_home_slow_in" TEXT,
    "diff_away_slow_in" TEXT,
    "diff_home_box_touch" TEXT,
    "diff_away_box_touch" TEXT,
    "diff_home_pass_count" TEXT,
    "diff_away_pass_count" TEXT,
    "diff_home_final_third_pass_count" TEXT,
    "diff_away_final_third_pass_count" TEXT,
    "diff_home_cross_count" TEXT,
    "diff_away_cross_count" TEXT,
    "diff_home_tackle_count" TEXT,
    "diff_away_tackle_count" TEXT,
    "diff_home_clear_count" TEXT,
    "diff_away_clear_count" TEXT,
    "diff_home_intercept_count" TEXT,
    "diff_away_intercept_count" TEXT,
    "home_play_style" TEXT,
    "away_play_style" TEXT,
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "scoring_playstyle_past_data_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "stat_encryption" (
    "id" BIGSERIAL NOT NULL,
    "country" TEXT,
    "league" TEXT,
    "home" TEXT,
    "away" TEXT,
    "team" TEXT,
    "chk_body" TEXT,
    "home_exp_info" TEXT,
    "away_exp_info" TEXT,
    "home_in_goal_exp_info" TEXT,
    "away_in_goal_exp_info" TEXT,
    "home_donation_info" TEXT,
    "away_donation_info" TEXT,
    "home_shoot_all_info" TEXT,
    "away_shoot_all_info" TEXT,
    "home_shoot_in_info" TEXT,
    "away_shoot_in_info" TEXT,
    "home_shoot_out_info" TEXT,
    "away_shoot_out_info" TEXT,
    "home_block_shoot_info" TEXT,
    "away_block_shoot_info" TEXT,
    "home_big_chance_info" TEXT,
    "away_big_chance_info" TEXT,
    "home_corner_info" TEXT,
    "away_corner_info" TEXT,
    "home_box_shoot_in_info" TEXT,
    "away_box_shoot_in_info" TEXT,
    "home_box_shoot_out_info" TEXT,
    "away_box_shoot_out_info" TEXT,
    "home_goal_post_info" TEXT,
    "away_goal_post_info" TEXT,
    "home_goal_head_info" TEXT,
    "away_goal_head_info" TEXT,
    "home_keeper_save_info" TEXT,
    "away_keeper_save_info" TEXT,
    "home_free_kick_info" TEXT,
    "away_free_kick_info" TEXT,
    "home_offside_info" TEXT,
    "away_offside_info" TEXT,
    "home_foul_info" TEXT,
    "away_foul_info" TEXT,
    "home_yellow_card_info" TEXT,
    "away_yellow_card_info" TEXT,
    "home_red_card_info" TEXT,
    "away_red_card_info" TEXT,
    "home_slow_in_info" TEXT,
    "away_slow_in_info" TEXT,
    "home_box_touch_info" TEXT,
    "away_box_touch_info" TEXT,
    "home_pass_count_info_on_success_count" TEXT,
    "away_pass_count_info_on_success_count" TEXT,
    "home_long_pass_count_info_on_success_count" TEXT,
    "away_long_pass_count_info_on_success_count" TEXT,
    "home_final_third_pass_count_info_on_success_count" TEXT,
    "away_final_third_pass_count_info_on_success_count" TEXT,
    "home_cross_count_info_on_success_count" TEXT,
    "away_cross_count_info_on_success_count" TEXT,
    "home_tackle_count_info_on_success_count" TEXT,
    "away_tackle_count_info_on_success_count" TEXT,
    "home_clear_count_info" TEXT,
    "away_clear_count_info" TEXT,
    "home_duel_count_info" TEXT,
    "away_duel_count_info" TEXT,
    "home_intercept_count_info" TEXT,
    "away_intercept_count_info" TEXT,
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "stat_encryption_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "stat_size_finalize_master" (
    "id" SERIAL NOT NULL,
    "option_num" VARCHAR(1) NOT NULL DEFAULT '0',
    "options" TEXT NOT NULL,
    "flg" VARCHAR(1) NOT NULL DEFAULT '0',
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "stat_size_finalize_master_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "surface_overview" (
    "id" SERIAL NOT NULL,
    "country" TEXT NOT NULL,
    "league" TEXT NOT NULL,
    "game_year" TEXT,
    "game_month" TEXT,
    "team" TEXT NOT NULL,
    "games" TEXT,
    "rank" TEXT,
    "win" TEXT,
    "lose" TEXT,
    "draw" TEXT,
    "winning_points" TEXT,
    "home_1st_half_score" TEXT,
    "home_2nd_half_score" TEXT,
    "home_sum_score" TEXT,
    "home_1st_half_score_ratio" TEXT,
    "home_2nd_half_score_ratio" TEXT,
    "home_clean_sheet" TEXT,
    "away_1st_half_score" TEXT,
    "away_2nd_half_score" TEXT,
    "away_sum_score" TEXT,
    "away_1st_half_score_ratio" TEXT,
    "away_2nd_half_score_ratio" TEXT,
    "away_clean_sheet" TEXT,
    "fail_to_score_game_count" TEXT,
    "consecutive_win_disp" TEXT,
    "consecutive_lose_disp" TEXT,
    "unbeaten_streak_count" TEXT,
    "unbeaten_streak_disp" TEXT,
    "consecutive_score_count" TEXT,
    "consecutive_score_count_disp" TEXT,
    "first_week_game_win_count" TEXT,
    "first_week_game_lost_count" TEXT,
    "first_week_game_win_disp" TEXT,
    "mid_week_game_win_count" TEXT,
    "mid_week_game_lost_count" TEXT,
    "mid_week_game_win_disp" TEXT,
    "last_week_game_win_count" TEXT,
    "last_week_game_lost_count" TEXT,
    "last_week_game_win_disp" TEXT,
    "home_win_count" TEXT,
    "home_lose_count" TEXT,
    "home_first_goal_count" TEXT,
    "home_win_behind_count" TEXT,
    "home_lose_behind_count" TEXT,
    "home_win_behind_0vs1_count" TEXT,
    "home_lose_behind_1vs0_count" TEXT,
    "home_win_behind_0vs2_count" TEXT,
    "home_lose_behind_2vs0_count" TEXT,
    "home_win_behind_other_count" TEXT,
    "home_lose_behind_other_count" TEXT,
    "home_adversity_disp" TEXT,
    "away_win_count" TEXT,
    "away_lose_count" TEXT,
    "away_first_goal_count" TEXT,
    "away_win_behind_count" TEXT,
    "away_lose_behind_count" TEXT,
    "away_win_behind_1vs0_count" TEXT,
    "away_lose_behind_0vs1_count" TEXT,
    "away_win_behind_2vs0_count" TEXT,
    "away_lose_behind_0vs2_count" TEXT,
    "away_win_behind_other_count" TEXT,
    "away_lose_behind_other_count" TEXT,
    "away_adversity_disp" VARCHAR(64),
    "promote_disp" VARCHAR(64),
    "descend_disp" VARCHAR(64),
    "first_win_disp" VARCHAR(64),
    "lose_streak_disp" VARCHAR(64),
    "round_conc" TEXT,
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "surface_overview_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "team_match_final_stats" (
    "seq" SERIAL NOT NULL,
    "team_name" TEXT,
    "versus_team_name" TEXT,
    "ha" VARCHAR(1),
    "score" TEXT,
    "result" TEXT,
    "game_fin_rank" TEXT,
    "opposite_game_fin_rank" TEXT,
    "exp" TEXT,
    "opposite_exp" TEXT,
    "in_goal_exp" TEXT,
    "opposite_in_goal_exp" TEXT,
    "donation" TEXT,
    "opposite_donation" TEXT,
    "shoot_all" TEXT,
    "opposite_shoot_all" TEXT,
    "shoot_in" TEXT,
    "opposite_shoot_in" TEXT,
    "shoot_out" TEXT,
    "opposite_shoot_out" TEXT,
    "block_shoot" TEXT,
    "opposite_block_shoot" TEXT,
    "big_chance" TEXT,
    "opposite_big_chance" TEXT,
    "corner" TEXT,
    "opposite_corner" TEXT,
    "box_shoot_in" TEXT,
    "opposite_box_shoot_in" TEXT,
    "box_shoot_out" TEXT,
    "opposite_box_shoot_out" TEXT,
    "goal_post" TEXT,
    "opposite_goal_post" TEXT,
    "goal_head" TEXT,
    "opposite_goal_head" TEXT,
    "keeper_save" TEXT,
    "opposite_keeper_save" TEXT,
    "free_kick" TEXT,
    "opposite_free_kick" TEXT,
    "offside" TEXT,
    "opposite_offside" TEXT,
    "foul" TEXT,
    "opposite_foul" TEXT,
    "yellow_card" TEXT,
    "opposite_yellow_card" TEXT,
    "red_card" TEXT,
    "opposite_red_card" TEXT,
    "slow_in" TEXT,
    "opposite_slow_in" TEXT,
    "box_touch" TEXT,
    "opposite_box_touch" TEXT,
    "pass_count_success_ratio" TEXT,
    "pass_count_success_count" TEXT,
    "pass_count_try_count" TEXT,
    "opposite_pass_count_success_ratio" TEXT,
    "opposite_pass_count_success_count" TEXT,
    "opposite_pass_count_try_count" TEXT,
    "long_pass_count_success_ratio" TEXT,
    "long_pass_count_success_count" TEXT,
    "long_pass_count_try_count" TEXT,
    "opposite_long_pass_count_success_ratio" TEXT,
    "opposite_long_pass_count_success_count" TEXT,
    "opposite_long_pass_count_try_count" TEXT,
    "final_third_pass_count_success_ratio" TEXT,
    "final_third_pass_count_success_count" TEXT,
    "final_third_pass_count_try_count" TEXT,
    "opposite_final_third_pass_count_success_ratio" TEXT,
    "opposite_final_third_pass_count_success_count" TEXT,
    "opposite_final_third_pass_count_try_count" TEXT,
    "cross_count_success_ratio" TEXT,
    "cross_count_success_count" TEXT,
    "cross_count_try_count" TEXT,
    "opposite_cross_count_success_ratio" TEXT,
    "opposite_cross_count_success_count" TEXT,
    "opposite_cross_count_try_count" TEXT,
    "tackle_count_success_ratio" TEXT,
    "tackle_count_success_count" TEXT,
    "tackle_count_try_count" TEXT,
    "opposite_tackle_count_success_ratio" TEXT,
    "opposite_tackle_count_success_count" TEXT,
    "opposite_tackle_count_try_count" TEXT,
    "clear_count" TEXT,
    "opposite_clear_count" TEXT,
    "duel_count" TEXT,
    "opposite_duel_count" TEXT,
    "intercept_count" TEXT,
    "opposite_intercept_count" TEXT,
    "weather" TEXT,
    "temperature" TEXT,
    "humid" TEXT,
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "team_match_final_stats_pkey" PRIMARY KEY ("seq")
);

-- CreateTable
CREATE TABLE "team_member_master" (
    "id" SERIAL NOT NULL,
    "country" TEXT,
    "league" TEXT,
    "team" TEXT NOT NULL,
    "score" TEXT,
    "loan_belong" TEXT,
    "jersey" TEXT NOT NULL,
    "member" TEXT NOT NULL,
    "face_pic_path" TEXT NOT NULL,
    "belong_list" TEXT,
    "height" TEXT,
    "weight" TEXT,
    "position" TEXT,
    "birth" TEXT,
    "age" TEXT,
    "market_value" TEXT,
    "injury" TEXT,
    "versus_team_score_data" TEXT,
    "retire_flg" CHAR(1),
    "deadline" CHAR(1),
    "deadline_contract_date" TEXT,
    "latest_info_date" TEXT,
    "upd_stamp" TEXT,
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "team_member_master_pkey" PRIMARY KEY ("id","team","jersey","member","face_pic_path")
);

-- CreateTable
CREATE TABLE "team_monthly_score_summary" (
    "seq" SERIAL NOT NULL,
    "country" TEXT,
    "league" TEXT,
    "team_name" TEXT,
    "ha" VARCHAR(1),
    "year" TEXT,
    "jar_sum_score" TEXT,
    "feb_sum_score" TEXT,
    "mar_sum_score" TEXT,
    "apr_sum_score" TEXT,
    "may_sum_score" TEXT,
    "jun_sum_score" TEXT,
    "jul_sum_score" TEXT,
    "aug_sum_score" TEXT,
    "sep_sum_score" TEXT,
    "oct_sum_score" TEXT,
    "nov_sum_score" TEXT,
    "dec_sum_score" TEXT,
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "team_monthly_score_summary_pkey" PRIMARY KEY ("seq")
);

-- CreateTable
CREATE TABLE "team_time_segment_shooting_stat" (
    "id" SERIAL NOT NULL,
    "data_category" TEXT,
    "team_name" TEXT,
    "away_team_name" TEXT,
    "team_0_10_mean_shoot_count" TEXT,
    "team_11_20_mean_shoot_count" TEXT,
    "team_21_30_mean_shoot_count" TEXT,
    "team_31_40_mean_shoot_count" TEXT,
    "team_41_45_mean_shoot_count" TEXT,
    "team_46_50_mean_shoot_count" TEXT,
    "team_51_60_mean_shoot_count" TEXT,
    "team_61_70_mean_shoot_count" TEXT,
    "team_71_80_mean_shoot_count" TEXT,
    "team_81_90_mean_shoot_count" TEXT,
    "team_addi_mean_shoot_count" TEXT,
    "team_0_10_mean_shoot_in_count" TEXT,
    "team_11_20_mean_shoot_in_count" TEXT,
    "team_21_30_mean_shoot_in_count" TEXT,
    "team_31_40_mean_shoot_in_count" TEXT,
    "team_41_45_mean_shoot_in_count" TEXT,
    "team_46_50_mean_shoot_in_count" TEXT,
    "team_51_60_mean_shoot_in_count" TEXT,
    "team_61_70_mean_shoot_in_count" TEXT,
    "team_71_80_mean_shoot_in_count" TEXT,
    "team_81_90_mean_shoot_in_count" TEXT,
    "team_addi_mean_shoot_in_count" TEXT,
    "team_0_10_mean_big_chance_count" TEXT,
    "team_11_20_mean_big_chance_count" TEXT,
    "team_21_30_mean_big_chance_count" TEXT,
    "team_31_40_mean_big_chance_count" TEXT,
    "team_41_45_mean_big_chance_count" TEXT,
    "team_46_50_mean_big_chance_count" TEXT,
    "team_51_60_mean_big_chance_count" TEXT,
    "team_61_70_mean_big_chance_count" TEXT,
    "team_71_80_mean_big_chance_count" TEXT,
    "team_81_90_mean_big_chance_count" TEXT,
    "team_addi_mean_big_chance_count" TEXT,
    "team_0_10_mean_free_kick_count" TEXT,
    "team_11_20_mean_free_kick_count" TEXT,
    "team_21_30_mean_free_kick_count" TEXT,
    "team_31_40_mean_free_kick_count" TEXT,
    "team_41_45_mean_free_kick_count" TEXT,
    "team_46_50_mean_free_kick_count" TEXT,
    "team_51_60_mean_free_kick_count" TEXT,
    "team_61_70_mean_free_kick_count" TEXT,
    "team_71_80_mean_free_kick_count" TEXT,
    "team_81_90_mean_free_kick_count" TEXT,
    "team_addi_mean_free_kick_count" TEXT,
    "team_0_10_mean_offside_count" TEXT,
    "team_11_20_mean_offside_count" TEXT,
    "team_21_30_mean_offside_count" TEXT,
    "team_31_40_mean_offside_count" TEXT,
    "team_41_45_mean_offside_count" TEXT,
    "team_46_50_mean_offside_count" TEXT,
    "team_51_60_mean_offside_count" TEXT,
    "team_61_70_mean_offside_count" TEXT,
    "team_71_80_mean_offside_count" TEXT,
    "team_81_90_mean_offside_count" TEXT,
    "team_addi_mean_offside_count" TEXT,
    "team_0_10_mean_foul_count" TEXT,
    "team_11_20_mean_foul_count" TEXT,
    "team_21_30_mean_foul_count" TEXT,
    "team_31_40_mean_foul_count" TEXT,
    "team_41_45_mean_foul_count" TEXT,
    "team_46_50_mean_foul_count" TEXT,
    "team_51_60_mean_foul_count" TEXT,
    "team_61_70_mean_foul_count" TEXT,
    "team_71_80_mean_foul_count" TEXT,
    "team_81_90_mean_foul_count" TEXT,
    "team_addi_mean_foul_count" TEXT,
    "team_0_10_mean_yellow_card_count" TEXT,
    "team_11_20_mean_yellow_card_count" TEXT,
    "team_21_30_mean_yellow_card_count" TEXT,
    "team_31_40_mean_yellow_card_count" TEXT,
    "team_41_45_mean_yellow_card_count" TEXT,
    "team_46_50_mean_yellow_card_count" TEXT,
    "team_51_60_mean_yellow_card_count" TEXT,
    "team_61_70_mean_yellow_card_count" TEXT,
    "team_71_80_mean_yellow_card_count" TEXT,
    "team_81_90_mean_yellow_card_count" TEXT,
    "team_addi_mean_yellow_card_count" TEXT,
    "team_0_10_mean_red_card_count" TEXT,
    "team_11_20_mean_red_card_count" TEXT,
    "team_21_30_mean_red_card_count" TEXT,
    "team_31_40_mean_red_card_count" TEXT,
    "team_41_45_mean_red_card_count" TEXT,
    "team_46_50_mean_red_card_count" TEXT,
    "team_51_60_mean_red_card_count" TEXT,
    "team_61_70_mean_red_card_count" TEXT,
    "team_71_80_mean_red_card_count" TEXT,
    "team_81_90_mean_red_card_count" TEXT,
    "team_addi_mean_red_card_count" TEXT,
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100) NOT NULL,
    "register_time" TIMESTAMPTZ(0) NOT NULL,
    "update_id" VARCHAR(100) NOT NULL,
    "update_time" TIMESTAMPTZ(0) NOT NULL,

    CONSTRAINT "team_time_segment_shooting_stat_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "within_data" (
    "id" SERIAL NOT NULL,
    "seq" VARCHAR(10),
    "time_range_feature_id" VARCHAR(3),
    "data_category" TEXT,
    "times" TEXT,
    "home_rank" TEXT,
    "home_team_name" TEXT,
    "home_score" TEXT DEFAULT '0',
    "away_rank" TEXT,
    "away_team_name" TEXT,
    "away_score" TEXT DEFAULT '0',
    "home_exp" TEXT,
    "away_exp" TEXT,
    "home_donation" TEXT,
    "away_donation" TEXT,
    "home_shoot_all" TEXT,
    "away_shoot_all" TEXT,
    "home_shoot_in" TEXT,
    "away_shoot_in" TEXT,
    "home_shoot_out" TEXT,
    "away_shoot_out" TEXT,
    "home_block_shoot" TEXT,
    "away_block_shoot" TEXT,
    "home_big_chance" TEXT,
    "away_big_chance" TEXT,
    "home_corner" TEXT,
    "away_corner" TEXT,
    "home_box_shoot_in" TEXT,
    "away_box_shoot_in" TEXT,
    "home_box_shoot_out" TEXT,
    "away_box_shoot_out" TEXT,
    "home_goal_post" TEXT,
    "away_goal_post" TEXT,
    "home_goal_head" TEXT,
    "away_goal_head" TEXT,
    "home_keeper_save" TEXT,
    "away_keeper_save" TEXT,
    "home_free_kick" TEXT,
    "away_free_kick" TEXT,
    "home_offside" TEXT,
    "away_offside" TEXT,
    "home_foul" TEXT,
    "away_foul" TEXT,
    "home_yellow_card" TEXT,
    "away_yellow_card" TEXT,
    "home_red_card" TEXT,
    "away_red_card" TEXT,
    "home_slow_in" TEXT,
    "away_slow_in" TEXT,
    "home_box_touch" TEXT,
    "away_box_touch" TEXT,
    "home_pass_count" TEXT,
    "away_pass_count" TEXT,
    "home_long_pass_count" TEXT,
    "away_long_pass_count" TEXT,
    "home_final_third_pass_count" TEXT,
    "away_final_third_pass_count" TEXT,
    "home_cross_count" TEXT,
    "away_cross_count" TEXT,
    "home_tackle_count" TEXT,
    "away_tackle_count" TEXT,
    "home_clear_count" TEXT,
    "away_clear_count" TEXT,
    "home_duel_count" TEXT,
    "away_duel_count" TEXT,
    "home_intercept_count" TEXT,
    "away_intercept_count" TEXT,
    "record_time" TIMESTAMP(0),
    "weather" TEXT,
    "temparature" TEXT,
    "humid" TEXT,
    "judge_member" TEXT,
    "home_manager" TEXT,
    "away_manager" TEXT,
    "home_formation" TEXT,
    "away_formation" TEXT,
    "studium" TEXT,
    "capacity" TEXT,
    "audience" TEXT,
    "home_max_getting_scorer" TEXT,
    "away_max_getting_scorer" TEXT,
    "home_max_getting_scorer_game_situation" TEXT,
    "away_max_getting_scorer_game_situation" TEXT,
    "home_team_home_score" TEXT,
    "home_team_home_lost" TEXT,
    "away_team_home_score" TEXT,
    "away_team_home_lost" TEXT,
    "home_team_away_score" TEXT,
    "home_team_away_lost" TEXT,
    "away_team_away_score" TEXT,
    "away_team_away_lost" TEXT,
    "notice_flg" TEXT,
    "goal_time" TEXT,
    "goal_team_member" TEXT,
    "judge" TEXT,
    "home_team_style" TEXT,
    "away_team_style" TEXT,
    "probablity" TEXT,
    "prediction_score_time" TEXT,
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "within_data_20minutes_away_all_league" (
    "id" SERIAL NOT NULL,
    "time_range" TEXT,
    "feature" TEXT,
    "threshold" TEXT,
    "target" TEXT,
    "search" TEXT,
    "ratio" TEXT,
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_20minutes_away_all_league_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "within_data_20minutes_away_scored" (
    "id" SERIAL NOT NULL,
    "country" TEXT,
    "category" TEXT,
    "time_range" TEXT,
    "feature" TEXT,
    "threshold" TEXT,
    "target" TEXT,
    "search" TEXT,
    "ratio" TEXT,
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_20minutes_away_scored_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "within_data_20minutes_home_all_league" (
    "id" SERIAL NOT NULL,
    "time_range" TEXT,
    "feature" TEXT,
    "threshold" TEXT,
    "target" TEXT,
    "search" TEXT,
    "ratio" TEXT,
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_20minutes_home_all_league_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "within_data_20minutes_home_scored" (
    "id" SERIAL NOT NULL,
    "country" TEXT,
    "category" TEXT,
    "time_range" TEXT,
    "feature" TEXT,
    "threshold" TEXT,
    "target" TEXT,
    "search" TEXT,
    "ratio" TEXT,
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_20minutes_home_scored_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "within_data_20minutes_same_scored" (
    "id" SERIAL NOT NULL,
    "country" TEXT,
    "category" TEXT,
    "time_range" TEXT,
    "feature" TEXT,
    "threshold" TEXT,
    "target" TEXT,
    "search" TEXT,
    "ratio" TEXT,
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_20minutes_same_scored_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "within_data_45minutes_away_all_league" (
    "id" SERIAL NOT NULL,
    "time_range" TEXT,
    "feature" TEXT,
    "threshold" TEXT,
    "target" TEXT,
    "search" TEXT,
    "ratio" TEXT,
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_45minutes_away_all_league_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "within_data_45minutes_away_scored" (
    "id" SERIAL NOT NULL,
    "country" TEXT,
    "category" TEXT,
    "time_range" TEXT,
    "feature" TEXT,
    "threshold" TEXT,
    "target" TEXT,
    "search" TEXT,
    "ratio" TEXT,
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_45minutes_away_scored_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "within_data_45minutes_home_all_league" (
    "id" SERIAL NOT NULL,
    "time_range" TEXT,
    "feature" TEXT,
    "threshold" TEXT,
    "target" TEXT,
    "search" TEXT,
    "ratio" TEXT,
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_45minutes_home_all_league_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "within_data_45minutes_home_scored" (
    "id" SERIAL NOT NULL,
    "country" TEXT,
    "category" TEXT,
    "time_range" TEXT,
    "feature" TEXT,
    "threshold" TEXT,
    "target" TEXT,
    "search" TEXT,
    "ratio" TEXT,
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "within_data_45minutes_home_scored_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "country_league_visibility" (
    "id" SERIAL NOT NULL,
    "country" VARCHAR(128) NOT NULL,
    "league" VARCHAR(128),
    "visible" BOOLEAN NOT NULL DEFAULT true,
    "priority" INTEGER NOT NULL DEFAULT 0,
    "reason" TEXT,
    "effectiveFrom" TIMESTAMPTZ(0),
    "effectiveTo" TIMESTAMPTZ(0),
    "optionId" INTEGER,
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "country_league_visibility_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "user_visibility_option" (
    "id" SERIAL NOT NULL,
    "userId" VARCHAR(64) NOT NULL,
    "optionId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "user_visibility_option_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "past_data_history" (
    "id" SERIAL NOT NULL,
    "situation" TEXT,
    "score" TEXT,
    "game_year" TEXT,
    "country" TEXT,
    "league" TEXT,
    "team" TEXT,
    "home_exp_stat" TEXT,
    "away_exp_stat" TEXT,
    "home_in_goal_exp_stat" TEXT,
    "away_in_goal_exp_stat" TEXT,
    "home_donation_stat" TEXT,
    "away_donation_stat" TEXT,
    "home_shoot_all_stat" TEXT,
    "away_shoot_all_stat" TEXT,
    "home_shoot_in_stat" TEXT,
    "away_shoot_in_stat" TEXT,
    "home_shoot_out_stat" TEXT,
    "away_shoot_out_stat" TEXT,
    "home_block_shoot_stat" TEXT,
    "away_block_shoot_stat" TEXT,
    "home_big_chance_stat" TEXT,
    "away_big_chance_stat" TEXT,
    "home_corner_stat" TEXT,
    "away_corner_stat" TEXT,
    "home_box_shoot_in_stat" TEXT,
    "away_box_shoot_in_stat" TEXT,
    "home_box_shoot_out_stat" TEXT,
    "away_box_shoot_out_stat" TEXT,
    "home_goal_post_stat" TEXT,
    "away_goal_post_stat" TEXT,
    "home_goal_head_stat" TEXT,
    "away_goal_head_stat" TEXT,
    "home_keeper_save_stat" TEXT,
    "away_keeper_save_stat" TEXT,
    "home_free_kick_stat" TEXT,
    "away_free_kick_stat" TEXT,
    "home_offside_stat" TEXT,
    "away_offside_stat" TEXT,
    "home_foul_stat" TEXT,
    "away_foul_stat" TEXT,
    "home_yellow_card_stat" TEXT,
    "away_yellow_card_stat" TEXT,
    "home_red_card_stat" TEXT,
    "away_red_card_stat" TEXT,
    "home_slow_in_stat" TEXT,
    "away_slow_in_stat" TEXT,
    "home_box_touch_stat" TEXT,
    "away_box_touch_stat" TEXT,
    "home_pass_count_stat" TEXT,
    "away_pass_count_stat" TEXT,
    "home_long_pass_count_stat" TEXT,
    "away_long_pass_count_stat" TEXT,
    "home_final_third_pass_count_stat" TEXT,
    "away_final_third_pass_count_stat" TEXT,
    "home_cross_count_stat" TEXT,
    "away_cross_count_stat" TEXT,
    "home_tackle_count_stat" TEXT,
    "away_tackle_count_stat" TEXT,
    "home_clear_count_stat" TEXT,
    "away_clear_count_stat" TEXT,
    "home_duel_count_stat" TEXT,
    "away_duel_count_stat" TEXT,
    "home_intercept_count_stat" TEXT,
    "away_intercept_count_stat" TEXT,
    "logic_flg" VARCHAR(1) DEFAULT '0',
    "register_id" VARCHAR(100),
    "register_time" TIMESTAMPTZ(0),
    "update_id" VARCHAR(100),
    "update_time" TIMESTAMPTZ(0),

    CONSTRAINT "past_data_history_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "country_league_UNIQUE" ON "country_league_summary"("country", "league");

-- CreateIndex
CREATE INDEX "idx_data_keys_times_seq" ON "data"("data_category", "home_team_name", "away_team_name", "times", "seq");

-- CreateIndex
CREATE INDEX "idx_lookup" ON "surface_overview"("country", "league", "game_year", "game_month", "team");

-- CreateIndex
CREATE UNIQUE INDEX "uk_team_month" ON "surface_overview"("country", "league", "team", "game_year", "game_month");

-- CreateIndex
CREATE INDEX "idx_web_visibility_lookup" ON "country_league_visibility"("country", "league");

-- CreateIndex
CREATE INDEX "idx_web_visibility_flag" ON "country_league_visibility"("visible");

-- CreateIndex
CREATE INDEX "idx_web_visibility_option" ON "country_league_visibility"("optionId");

-- CreateIndex
CREATE UNIQUE INDEX "uk_web_visibility_scoped" ON "country_league_visibility"("country", "league", "optionId");

-- CreateIndex
CREATE INDEX "idx_user_option_user" ON "user_visibility_option"("userId");

-- CreateIndex
CREATE INDEX "idx_user_option_option" ON "user_visibility_option"("optionId");

-- CreateIndex
CREATE UNIQUE INDEX "uk_user_option" ON "user_visibility_option"("userId", "optionId");

-- AddForeignKey
ALTER TABLE "country_league_visibility" ADD CONSTRAINT "country_league_visibility_optionId_fkey" FOREIGN KEY ("optionId") REFERENCES "stat_size_finalize_master"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_visibility_option" ADD CONSTRAINT "user_visibility_option_optionId_fkey" FOREIGN KEY ("optionId") REFERENCES "stat_size_finalize_master"("id") ON DELETE CASCADE ON UPDATE CASCADE;
